apiVersion: 1

datasources:
  - name: influxdb
    type: influxdb
    access: proxy
    url: http://198.18.140.3:8086
    isDefault: true
    basicAuth: true
    basicAuthUser: netadmin
    secureJsonData:
      basicAuthPassword: C1sco12345!
    jsonData:
      dbName: telemetry
    editable: true
    uid: fdlxypdqnwr28e

  - name: influxdb-FLUX
    type: influxdb
    access: proxy
    url: http://198.18.140.3:8086
    isDefault: false
    basicAuth: true
    basicAuthUser: netadmin
    secureJsonData:
      basicAuthPassword: C1sco12345!
      token: C1sco12345!
    jsonData:
      httpMode: POST
      organization: lab
      version: Flux
    editable: true
    uid: edmi7f4dpg2yof