{
 "title": "VC-CAR - Cisco 8201 - 02 - Power",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Fan Status",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "\nfrom(bucket: \"telemetry\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Cisco-IOS-XR-platform-oper:platform/racks/rack/slots/slot/state\")\n\n  |> filter(fn: (r) => r[\"path\"] == \"Cisco-IOS-XR-platform-oper:platform/racks/rack/slots/slot/state\")\n\n  |> tail(n: 4)\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> group()\n  |> drop(columns:[\"subscription\", \"path\",\"_measurement\",\"host\",\"source\",\"_start\",\"_stop\",\"_field\",\"rack_name\",\"state\",\"card_redundancy_state\"])\n  |> sort(columns: [\"_time\"], desc: true)\n  |> rename(columns: {_time: \"time\"}) \n"
    }
   ]
  },
  {
   "title": "Power Supplies status",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "from(bucket: \"telemetry\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Cisco-IOS-XR-platform-oper:platform/racks/rack/slots/slot/state\")\n  |> filter(fn: (r) => r[\"path\"] == \"Cisco-IOS-XR-platform-oper:platform/racks/rack/slots/slot/state\")\n  |> filter(fn: (r) => r[\"slot_name\"] == \"PM0\" or r[\"slot_name\"] == \"PM1\")  // Filter for PM0 and PM1\n  |> tail(n: 4)\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> group()\n  |> drop(columns:[\"subscription\", \"path\",\"_measurement\",\"host\",\"source\",\"_start\",\"_stop\",\"_field\",\"rack_name\",\"state\",\"card_redundancy_state\"])\n  |> sort(columns: [\"_time\"], desc: true)\n  |> rename(columns: {_time: \"time\"})"
    }
   ]
  },
  {
   "title": "Power Sensors",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 17, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "\nfrom(bucket: \"telemetry\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => \n    r._measurement == \"Cisco-IOS-XR-envmon-oper:environmental-monitoring/rack/nodes/node/sensor-types/sensor-type/sensor-names/sensor-name\" and \n    (r._field == \"sensor_value\")\n  )\n  |> filter(fn: (r) => r.type == \"power\")\n  |> keep(columns: [\"_field\", \"_value\", \"_time\", \"node\", \"location\", \"name\", \"type\", \"source\"])\n"
    }
   ]
  },
  {
   "title": "Power Efficiency",
   "type": "bargauge",
   "gridPos": { "h": 13, "w": 7, "x": 17, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"telemetry\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => \n    r._measurement == \"Cisco-IOS-XR-envmon-oper:environmental-monitoring/rack/nodes/node/sensor-types/sensor-type/sensor-names/sensor-name\" and \n    (\n      r._field == \"sensor_value\" and \n      (r.name == \"Input_Power\" or r.name == \"Output_Power\") and\n      (r.node == \"0/PM0\" or r.node == \"0/PM1\")\n    )\n  )\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"name\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({\n    r with\n    _value: (float(v: r.Output_Power) / float(v: r.Input_Power)) * 100.0\n  }))\n  |> drop(columns: [\"Input_Power\", \"Output_Power\"])"
    }
   ]
  },
  {
   "title": "Voltage",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "mvolt" } },
   "targets": [
    {
     "query": "\nfrom(bucket: \"telemetry\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => \n    r._measurement == \"Cisco-IOS-XR-envmon-oper:environmental-monitoring/rack/nodes/node/sensor-types/sensor-type/sensor-names/sensor-name\" and \n    (r._field == \"sensor_value\")\n  )\n  |> filter(fn: (r) => r.type == \"voltage\")\n  |> keep(columns: [\"_field\", \"_value\", \"_time\", \"node\", \"location\", \"name\", \"type\", \"source\"])\n\n\n\n"
    }
   ]
  },
  {
   "title": "Current",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "mamp" } },
   "targets": [
    {
     "query": "from(bucket: \"telemetry\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => \n       r._measurement == \"Cisco-IOS-XR-envmon-oper:environmental-monitoring/rack/nodes/node/sensor-types/sensor-type/sensor-names/sensor-name\" and \n       r._field == \"sensor_value\"\n  )\n  |> filter(fn: (r) => r.type == \"current\")\n  // Combine filters for 'name' field to include both 'Input_Cur' and 'Input_Curr'\n  |> filter(fn: (r) => \n       r[\"name\"] == \"Input_Cur\" or \n       r[\"name\"] == \"Input_Curr\"\n  )\n  |> keep(columns: [\"_field\", \"_value\", \"_time\", \"node\", \"location\", \"name\", \"type\", \"source\"])"
    }
   ]
  }
 ]
}