{
 "title": "VC-CAR - Cisco 8201 - 01 - Platform",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Hostname",
   "type": "stat",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Cisco-IOS-XR-shellutil-oper:system-time/uptime",
     "query": "from(bucket: \"telemetry\")\n  |> range(start: -15m)\n  |> filter(fn: (r) => r._measurement == \"Cisco-IOS-XR-shellutil-oper:system-time/uptime\")\n  |> filter(fn: (r) => r._field == \"host_name\")\n  |> filter(fn: (r) => r.path == \"Cisco-IOS-XR-shellutil-oper:system-time/uptime\")  \n  |> filter(fn: (r) => r.source == \"rtp-cpoc-AWS-SELAB-8201-32FH-1\")\n  |> keep(columns: [\"_value\"]) \n  |> yield(name: \"last\")\n",
     "select": [
      [
       { "params": [ "host_name" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Chassis PID",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 13, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"telemetry\")\n  |> range(start: -15m) // Adjust the time range as needed\n  |> filter(fn: (r) => r._measurement == \"Cisco-IOS-XR-install-augmented-oper:install/version/brief\")\n  |> filter(fn: (r) => r._field == \"chassis_pid\")\n  |> filter(fn: (r) => r.path == \"Cisco-IOS-XR-install-augmented-oper:install/version/brief\")\n  |> keep(columns: [\"_time\", \"_value\"]) // Keep the _time column\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\") \n"
    }
   ]
  },
  {
   "title": "IOS XR Version",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"telemetry\")\n  |> range(start: -15m) // Adjust the time range as needed\n  |> filter(fn: (r) => r._measurement == \"Cisco-IOS-XR-install-augmented-oper:install/version/brief\")\n  |> filter(fn: (r) => r._field == \"label\")\n  |> filter(fn: (r) => r.path == \"Cisco-IOS-XR-install-augmented-oper:install/version/brief\")\n  |> keep(columns: [\"_time\", \"_value\"]) // Keep the _time column\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\") \n"
    }
   ]
  },
  {
   "title": "Platform Status",
   "type": "table",
   "gridPos": { "h": 16, "w": 13, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "\nfrom(bucket: \"telemetry\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Cisco-IOS-XR-platform-oper:platform/racks/rack/slots/slot/state\")\n  |> filter(fn: (r) => r[\"path\"] == \"Cisco-IOS-XR-platform-oper:platform/racks/rack/slots/slot/state\")\n  |> tail(n: 4)\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> group()\n  |> drop(columns:[\"subscription\", \"path\",\"_measurement\",\"host\",\"source\",\"_start\",\"_stop\",\"_field\",\"rack_name\",\"state\",\"card_redundancy_state\"])\n  |> sort(columns: [\"_time\"], desc: true)\n  |> rename(columns: {_time: \"time\"}) \n"
    }
   ]
  },
  {
   "title": "Chassis Description",
   "type": "stat",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"telemetry\")\n  |> range(start: -15m) // Adjust the time range as needed\n  |> filter(fn: (r) => r._measurement == \"Cisco-IOS-XR-install-augmented-oper:install/version/brief\")\n  |> filter(fn: (r) => r._field == \"chassis_description\")\n  |> filter(fn: (r) => r.path == \"Cisco-IOS-XR-install-augmented-oper:install/version/brief\")\n  |> keep(columns: [\"_time\", \"_value\"]) // Keep the _time column\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\") \n"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"telemetry\")\n  |> range(start: -15m) // Adjust the time range as needed\n  |> filter(fn: (r) => r._measurement == \"Cisco-IOS-XR-install-augmented-oper:install/version/brief\")\n  |> filter(fn: (r) => r._field == \"uptime\")\n  |> filter(fn: (r) => r.path == \"Cisco-IOS-XR-install-augmented-oper:install/version/brief\")\n  |> keep(columns: [\"_time\", \"_value\"]) // Keep the _time column\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\") \n"
    }
   ]
  },
  {
   "title": "Platform Status",
   "type": "table",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "\n\nfrom(bucket: \"telemetry\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Cisco-IOS-XR-platform-oper:platform/racks/rack/slots/slot/instances/instance/state\")\n  |> filter(fn: (r) => r[\"path\"] == \"Cisco-IOS-XR-platform-oper:platform/racks/rack/slots/slot/instances/instance/state\")\n  |> tail(n: 4)\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> group()\n  |> drop(columns:[\"subscription\", \"path\",\"_measurement\",\"host\",\"source\",\"_start\",\"_stop\",\"_field\",\"rack_name\",\"state\",\"card_redundancy_state\"])\n  |> sort(columns: [\"_time\"], desc: true)\n  |> rename(columns: {_time: \"time\"}) \n"
    }
   ]
  },
  {
   "title": "CPU Model",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 13, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"telemetry\")\n  |> range(start: -15m) // Adjust the time range as needed\n  |> filter(fn: (r) => r._measurement == \"Cisco-IOS-XR-install-augmented-oper:install/version/brief\")\n  |> filter(fn: (r) => r._field == \"processor\")\n  |> filter(fn: (r) => r.path == \"Cisco-IOS-XR-install-augmented-oper:install/version/brief\")\n  |> keep(columns: [\"_time\", \"_value\"]) // Keep the _time column\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\") \n"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 17, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"telemetry\")\n  |> range(start: -15m) // Adjust the time range as needed\n  |> filter(fn: (r) => r._measurement == \"Cisco-IOS-XR-install-augmented-oper:install/version/brief\")\n  |> filter(fn: (r) => r._field == \"total_ram\")\n  |> filter(fn: (r) => r.path == \"Cisco-IOS-XR-install-augmented-oper:install/version/brief\")\n  |> keep(columns: [\"_time\", \"_value\"]) // Keep the _time column\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\") \n"
    }
   ]
  },
  {
   "title": "Available RAM",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"telemetry\")\n  |> range(start: -15m) // Adjust the time range as needed\n  |> filter(fn: (r) => r._measurement == \"Cisco-IOS-XR-nto-misc-oper:memory-summary/nodes/node/summary\")\n  |> filter(fn: (r) => r._field == \"free_physical_memory\")\n  |> keep(columns: [\"_time\", \"_value\"]) // Keep the _time column\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\") \n"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "\nfrom(bucket: \"telemetry\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => \n    r._measurement == \"Cisco-IOS-XR-envmon-oper:environmental-monitoring/rack/nodes/node/sensor-types/sensor-type/sensor-names/sensor-name\" and \n    (r._field == \"sensor_value\")\n  )\n  |> filter(fn: (r) => r.type == \"temperature\")\n  |> keep(columns: [\"_field\", \"_value\", \"_time\", \"node\", \"location\", \"name\", \"type\", \"source\"])\n\n\n\n"
    }
   ]
  },
  {
   "title": "Fans",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "targets": [
    {
     "query": "\nfrom(bucket: \"telemetry\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => \n    r._measurement == \"Cisco-IOS-XR-envmon-oper:environmental-monitoring/rack/nodes/node/sensor-types/sensor-type/sensor-names/sensor-name\" and \n    (r._field == \"sensor_value\")\n  )\n  |> filter(fn: (r) => r.type == \"fan\")\n  |> keep(columns: [\"_field\", \"_value\", \"_time\", \"node\", \"location\", \"name\", \"type\", \"source\"])\n\n\n\n"
    }
   ]
  },
  {
   "title": "CPU : 0/RP0/CPU0 - Graph",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 15, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" }
     ],
     "measurement": "Cisco-IOS-XR-shellutil-oper:system-time/uptime",
     "query": "from(bucket: \"telemetry\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Cisco-IOS-XR-wdsysmon-fd-oper:system-monitoring/cpu-utilization\")\n  |> filter(fn: (r) => r[\"_field\"] == \"total_cpu_one_minute\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "uptime" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU : 0/RP0/CPU0 : 1min",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 15, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" }
     ],
     "measurement": "Cisco-IOS-XR-shellutil-oper:system-time/uptime",
     "query": "from(bucket: \"telemetry\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Cisco-IOS-XR-wdsysmon-fd-oper:system-monitoring/cpu-utilization\")\n  |> filter(fn: (r) => r[\"_field\"] == \"total_cpu_one_minute\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "uptime" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU : 0/RP0/CPU0 : 5mins",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 18, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" }
     ],
     "measurement": "Cisco-IOS-XR-shellutil-oper:system-time/uptime",
     "query": "from(bucket: \"telemetry\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Cisco-IOS-XR-wdsysmon-fd-oper:system-monitoring/cpu-utilization\")\n  |> filter(fn: (r) => r[\"_field\"] == \"total_cpu_five_minute\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "uptime" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU : 0/RP0/CPU0 : 15mins",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 21, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" }
     ],
     "measurement": "Cisco-IOS-XR-shellutil-oper:system-time/uptime",
     "query": "from(bucket: \"telemetry\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Cisco-IOS-XR-wdsysmon-fd-oper:system-monitoring/cpu-utilization\")\n  |> filter(fn: (r) => r[\"_field\"] == \"total_cpu_fifteen_minute\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "uptime" ], "type": "field" }
      ]
     ]
    }
   ]
  }
 ]
}