{
 "title": "VC-CAR - Cisco 8201 - 01 - Platform",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Hostname",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "Cisco-IOS-XR-shellutil-oper:system-time/uptime",
     "query": "SELECT last(\"host_name\") FROM \"Cisco-IOS-XR-shellutil-oper:system-time/uptime\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "host_name" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Chassis PID",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" }
     ],
     "measurement": "Cisco-IOS-XR-shellutil-oper:system-time/uptime",
     "query": "from(bucket: \"telemetry\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Cisco-IOS-XR-install-augmented-oper:install/version/brief\")\n  |> filter(fn: (r) => r[\"_field\"] == \"chassis_pid\")\n  |> filter(fn: (r) => r[\"host\"] == \"91f8036908e4\")\n  |> filter(fn: (r) => r[\"path\"] == \"Cisco-IOS-XR-install-augmented-oper:install/version/brief\")\n  |> filter(fn: (r) => r[\"source\"] == \"rtp-cpoc-AWS-SELAB-8201-32FH-1\")\n  |> filter(fn: (r) => r[\"subscription\"] == \"PLATFORM-SUB\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "uptime" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "IOS XR Version",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" }
     ],
     "measurement": "Cisco-IOS-XR-shellutil-oper:system-time/uptime",
     "query": "from(bucket: \"telemetry\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Cisco-IOS-XR-install-augmented-oper:install/version/brief\")\n  |> filter(fn: (r) => r[\"_field\"] == \"label\")\n  |> filter(fn: (r) => r[\"host\"] == \"91f8036908e4\")\n  |> filter(fn: (r) => r[\"path\"] == \"Cisco-IOS-XR-install-augmented-oper:install/version/brief\")\n  |> filter(fn: (r) => r[\"source\"] == \"rtp-cpoc-AWS-SELAB-8201-32FH-1\")\n  |> filter(fn: (r) => r[\"subscription\"] == \"PLATFORM-SUB\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "uptime" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Platform Status",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "\nfrom(bucket: \"telemetry\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Cisco-IOS-XR-platform-oper:platform/racks/rack/slots/slot/state\")\n\n  |> filter(fn: (r) => r[\"path\"] == \"Cisco-IOS-XR-platform-oper:platform/racks/rack/slots/slot/state\")\n\n  |> tail(n: 4)\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> group()\n  |> drop(columns:[\"subscription\", \"path\",\"_measurement\",\"host\",\"source\",\"_start\",\"_stop\",\"_field\",\"rack_name\",\"state\",\"card_redundancy_state\"])\n  |> sort(columns: [\"_time\"], desc: true)\n  |> rename(columns: {_time: \"time\"}) \n"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" }
     ],
     "measurement": "Cisco-IOS-XR-shellutil-oper:system-time/uptime",
     "query": "from(bucket: \"telemetry\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Cisco-IOS-XR-install-augmented-oper:install/version/brief\")\n  |> filter(fn: (r) => r[\"_field\"] == \"uptime\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")\n\n",
     "select": [
      [
       { "params": [ "uptime" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU Model",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" }
     ],
     "measurement": "Cisco-IOS-XR-shellutil-oper:system-time/uptime",
     "query": "from(bucket: \"telemetry\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Cisco-IOS-XR-install-augmented-oper:install/version/brief\")\n  |> filter(fn: (r) => r[\"_field\"] == \"processor\")\n  |> filter(fn: (r) => r[\"host\"] == \"91f8036908e4\")\n  |> filter(fn: (r) => r[\"path\"] == \"Cisco-IOS-XR-install-augmented-oper:install/version/brief\")\n  |> filter(fn: (r) => r[\"source\"] == \"rtp-cpoc-AWS-SELAB-8201-32FH-1\")\n  |> filter(fn: (r) => r[\"subscription\"] == \"PLATFORM-SUB\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "uptime" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" }
     ],
     "measurement": "Cisco-IOS-XR-shellutil-oper:system-time/uptime",
     "query": "from(bucket: \"telemetry\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Cisco-IOS-XR-install-augmented-oper:install/version/brief\")\n  |> filter(fn: (r) => r[\"_field\"] == \"total_ram\")\n  |> filter(fn: (r) => r[\"host\"] == \"91f8036908e4\")\n  |> filter(fn: (r) => r[\"path\"] == \"Cisco-IOS-XR-install-augmented-oper:install/version/brief\")\n  |> filter(fn: (r) => r[\"source\"] == \"rtp-cpoc-AWS-SELAB-8201-32FH-1\")\n  |> filter(fn: (r) => r[\"subscription\"] == \"PLATFORM-SUB\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "uptime" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU : 0/RP0/CPU0 : 1min",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" }
     ],
     "measurement": "Cisco-IOS-XR-shellutil-oper:system-time/uptime",
     "query": "from(bucket: \"telemetry\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Cisco-IOS-XR-wdsysmon-fd-oper:system-monitoring/cpu-utilization\")\n  |> filter(fn: (r) => r[\"_field\"] == \"total_cpu_one_minute\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "uptime" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU : 0/RP0/CPU0 : 5mins",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 7, "x": 5, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" }
     ],
     "measurement": "Cisco-IOS-XR-shellutil-oper:system-time/uptime",
     "query": "from(bucket: \"telemetry\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Cisco-IOS-XR-wdsysmon-fd-oper:system-monitoring/cpu-utilization\")\n  |> filter(fn: (r) => r[\"_field\"] == \"total_cpu_five_minute\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "uptime" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Platform Status",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "\n\nfrom(bucket: \"telemetry\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Cisco-IOS-XR-platform-oper:platform/racks/rack/slots/slot/instances/instance/state\")\n  |> filter(fn: (r) => r[\"path\"] == \"Cisco-IOS-XR-platform-oper:platform/racks/rack/slots/slot/instances/instance/state\")\n  |> tail(n: 4)\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> group()\n  |> drop(columns:[\"subscription\", \"path\",\"_measurement\",\"host\",\"source\",\"_start\",\"_stop\",\"_field\",\"rack_name\",\"state\",\"card_redundancy_state\"])\n  |> sort(columns: [\"_time\"], desc: true)\n  |> rename(columns: {_time: \"time\"}) \n"
    }
   ]
  },
  {
   "title": "CPU : 0/RP0/CPU0 : 15mins",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" }
     ],
     "measurement": "Cisco-IOS-XR-shellutil-oper:system-time/uptime",
     "query": "from(bucket: \"telemetry\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Cisco-IOS-XR-wdsysmon-fd-oper:system-monitoring/cpu-utilization\")\n  |> filter(fn: (r) => r[\"_field\"] == \"total_cpu_fifteen_minute\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "uptime" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "\nfrom(bucket: \"telemetry\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => \n    r._measurement == \"Cisco-IOS-XR-envmon-oper:environmental-monitoring/rack/nodes/node/sensor-types/sensor-type/sensor-names/sensor-name\" and \n    (r._field == \"sensor_value\")\n  )\n  |> filter(fn: (r) => r.type == \"temperature\")\n  |> keep(columns: [\"_field\", \"_value\", \"_time\", \"node\", \"location\", \"name\", \"type\", \"source\"])\n\n\n\n"
    }
   ]
  },
  {
   "title": "Fan 0 - Speed",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Cisco-IOS-XR-envmon-oper:environmental-monitoring/rack/nodes/node/sensor-types/sensor-type/sensor-names/sensor-name",
     "select": [
      [
       { "params": [ "sensor_value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "source::tag", "operator": "=", "value": "rtp-cpoc-AWS-SELAB-8201-32FH-1" },
      { "condition": "AND", "key": "name::tag", "operator": "=", "value": "FAN_0_Speed" }
     ]
    }
   ]
  },
  {
   "title": "Platform Status",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "\n\nfrom(bucket: \"telemetry\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Cisco-IOS-XR-platform-oper:platform/racks/rack/slots/slot/instances/instance/state\")\n  |> filter(fn: (r) => r[\"path\"] == \"Cisco-IOS-XR-platform-oper:platform/racks/rack/slots/slot/instances/instance/state\")\n  |> tail(n: 4)\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> group()\n  |> drop(columns:[\"subscription\", \"path\",\"_measurement\",\"host\",\"source\",\"_start\",\"_stop\",\"_field\",\"rack_name\",\"state\",\"card_redundancy_state\"])\n  |> sort(columns: [\"_time\"], desc: true)\n  |> rename(columns: {_time: \"time\"}) \n"
    }
   ]
  },
  {
   "title": "SSD Temperature",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Cisco-IOS-XR-envmon-oper:environmental-monitoring/rack/nodes/node/sensor-types/sensor-type/sensor-names/sensor-name",
     "select": [
      [
       { "params": [ "sensor_value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "source::tag", "operator": "=", "value": "rtp-cpoc-AWS-SELAB-8201-32FH-1" },
      { "condition": "AND", "key": "name::tag", "operator": "=", "value": "SSD_Temp" }
     ]
    }
   ]
  },
  {
   "title": "Memory - DIMM 01 - Temperature",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 3, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Cisco-IOS-XR-envmon-oper:environmental-monitoring/rack/nodes/node/sensor-types/sensor-type/sensor-names/sensor-name",
     "select": [
      [
       { "params": [ "sensor_value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "source::tag", "operator": "=", "value": "rtp-cpoc-AWS-SELAB-8201-32FH-1" },
      { "condition": "AND", "key": "name::tag", "operator": "=", "value": "DIMM_TEMP1" }
     ]
    }
   ]
  },
  {
   "title": "Fan 0 - Speed",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Cisco-IOS-XR-envmon-oper:environmental-monitoring/rack/nodes/node/sensor-types/sensor-type/sensor-names/sensor-name",
     "query": "from(bucket: \"primary_bucket\")\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n|> filter(fn: (r) => r[\"_measurement\"] == \"Cisco-IOS-XR-envmon-oper:environmental-monitoring/rack/nodes/node/sensor-types/sensor-type/sensor-names/sensor-name\")\n|> filter(fn: (r) => r[\"source\"] == \"rtp-cpoc-AWS-SELAB-8201-32FH-1\")\n|> filter(fn: (r) => r[\"node\"] == \"0/RP0/CPU0\")\n|> filter(fn: (r) => r[\"type\"] == \"temperature\")\n|> filter(fn: (r) => r[\"_field\"] == \"sensor_value\")\n|> drop(columns: [\"host\", \"path\", \"node\", \"source\", \"type\" , \"name\"])\n|> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n|> yield(name: \"mean\")\n\n\n",
     "select": [
      [
       { "params": [ "sensor_value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "source::tag", "operator": "=", "value": "rtp-cpoc-AWS-SELAB-8201-32FH-1" },
      { "condition": "AND", "key": "name::tag", "operator": "=", "value": "FAN_0_Speed" }
     ]
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 74 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" }
     ],
     "measurement": "Cisco-IOS-XR-shellutil-oper:system-time/uptime",
     "query": "SELECT \"uptime\"  FROM \"Cisco-IOS-XR-shellutil-oper:system-time/uptime\" WHERE $timeFilter\n",
     "select": [
      [
       { "params": [ "uptime" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Fan 1 - Speed",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Cisco-IOS-XR-envmon-oper:environmental-monitoring/rack/nodes/node/sensor-types/sensor-type/sensor-names/sensor-name",
     "select": [
      [
       { "params": [ "sensor_value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "source::tag", "operator": "=", "value": "rtp-cpoc-AWS-SELAB-8201-32FH-1" },
      { "condition": "AND", "key": "name::tag", "operator": "=", "value": "FAN_1_Speed" }
     ]
    }
   ]
  },
  {
   "title": "Heatsing temp",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Cisco-IOS-XR-envmon-oper:environmental-monitoring/rack/nodes/node/sensor-types/sensor-type/sensor-names/sensor-name",
     "select": [
      [
       { "params": [ "sensor_value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "source::tag", "operator": "=", "value": "rtp-cpoc-AWS-SELAB-8201-32FH-1" },
      { "condition": "AND", "key": "name::tag", "operator": "=", "value": "HSNK_Temp" }
     ]
    }
   ]
  },
  {
   "title": "Memory - DIMM 02 - Temperature",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Cisco-IOS-XR-envmon-oper:environmental-monitoring/rack/nodes/node/sensor-types/sensor-type/sensor-names/sensor-name",
     "select": [
      [
       { "params": [ "sensor_value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "source::tag", "operator": "=", "value": "rtp-cpoc-AWS-SELAB-8201-32FH-1" },
      { "condition": "AND", "key": "name::tag", "operator": "=", "value": "DIMM_TEMP2" }
     ]
    }
   ]
  },
  {
   "title": "Memory - DIMM 02 - Temperature",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 106 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Cisco-IOS-XR-envmon-oper:environmental-monitoring/rack/nodes/node/sensor-types/sensor-type/sensor-names/sensor-name",
     "select": [
      [
       { "params": [ "sensor_value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "source::tag", "operator": "=", "value": "rtp-cpoc-AWS-SELAB-8201-32FH-1" },
      { "condition": "AND", "key": "name::tag", "operator": "=", "value": "DIMM_TEMP2" }
     ]
    }
   ]
  }
 ]
}