{
 "title": "Carbon emissions - new version",
 "time": { "from": "now-1m", "to": "now" },
 "refresh": "5m",
 "panels": [
  { "title": "Last 1d", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Last 24 hours",
   "type": "bargauge",
   "description": "At 1AM of next day shows the total of the previous day. Last value (for incomplete time window) is shown in the legend.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "massg" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"dict\"\nimport \"date\" //import library to add date functions\n\n//months = [1:\"January\",2:\"February\",3:\"March\",4:\"April\",5:\"May\",6:\"June\",7:\"July\",8:\"August\",9:\"September\",10:\"October\",11:\"November\",12: \"December\"]\n//days = [0:\"Sunday\", 1:\"Monday\", 2:\"Tuesday\", 3:\"Wednesday\", 4:\"Thursday\",5:\"Friday\", 6:\"Saturday\"]\n\ntimeIntervalkWh = 1h\ntimeInterval = 1h\ntimeRange = 25h\n\nsrc = from(bucket: \"bucket1\")\n  |> range(start: -timeRange)\n  |> filter(fn: (r) =>\n  r._measurement == \"Cisco-IOS-XR-sysadmin-fretta-envmon-ui:environment/oper/power/location/pem_attributes\" and\n  r._field == \"system_power_input\" and r.source != \"Ravello-51\")\n  |> window(every: timeIntervalkWh)\n  |> mean()\n  |> duplicate(column: \"_start\", as: \"_time\")\n\nco2eqkwh = from(bucket: \"bucket1\")\n  |> range(start: -timeRange)\n  |> filter(fn: (r) =>\n  \t  r._measurement == \"electricity-map\" and\n      r._field == \"carbonIntensity\")\n  |> drop(columns: [\"_measurement\"])\n  |> window(every: timeIntervalkWh)\n  |> mean()\n  |> duplicate(column: \"_start\", as: \"_time\")\n  |> drop(columns: [\"_measurement\"])\n  |> keep(columns: [\"_value\", \"_time\", \"cc\", \"country\", \"region\"])\n\nj = join(\n\ttables: {t1: src, t2: co2eqkwh},\n    on: [\"cc\", \"_time\"],\n\t)\n  |> map(fn: (r) => ({\n    r with\n      //system_power_input: r._value_t1,\n      //carbonIntensity: r._value_t2,\n      region: r.region_t1,\n      country: r.country_t1,\n      _value: float(v: r._value_t1) * float(v: r._value_t2) / 1000.0,\n  }))\n  |> keep(columns: [\"_value\", \"_time\",\"source\"])\n  |> group()\n  |> aggregateWindow(every: timeInterval, fn: sum)\n  |> keep(columns: [\"_value\", \"_time\"])\n  |> map(fn: (r) => ({ r with //Valuemapping of monthnumber to monthname\n    namedHour: date.hour(t: r._time)\n  }))\n  |> keep(columns: [\"_value\", \"source\", \"namedHour\", \"_time\"])\n  |> group(columns: [\"namedHour\"])\n  |> first() // Trick to avoid double measurements from the last bucket\n  |> group()\n  |> sort(columns: [\"_time\"], desc: false)\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"namedHour\"], valueColumn: \"_value\") //formatting for Grafana\n  |> yield()"
    }
   ]
  },
  {
   "title": "Last 24 h per device",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "massg" } },
   "targets": [
    {
     "query": "// Look at last 26h because during the aggregations we lose 2 hrs.\n\nsrc = from(bucket: \"bucket1\")\n  //|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  //|> range(start: -25h, stop: -1h)\n  |> range(start: -26h)\n  |> filter(fn: (r) =>\n  r._measurement == \"Cisco-IOS-XR-sysadmin-fretta-envmon-ui:environment/oper/power/location/pem_attributes\" and\n  r._field == \"system_power_input\" and r.source != \"Ravello-51\")\n  ////|> aggregateWindow(every: 1h, fn: mean)\n  //|> keep(columns: [\"_value\", \"_time\",\"source\"])\n  |> window(every: 1h)\n  |> mean()\n  |> duplicate(column: \"_stop\", as: \"_time\")\n  |> keep(columns: [\"_value\", \"_time\",\"source\", \"cc\", \"country\", \"region\", \"measurement\"])\n  \n\nco2eqkwh = from(bucket: \"bucket1\")\n  //|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  //|> range(start: -25h, stop: -1h)\n  |> range(start: -26h)\n  |> filter(fn: (r) =>\n  \t  r._measurement == \"electricity-map\" and\n      r._field == \"carbonIntensity\")\n  |> window(every: 1h)\n  |> mean()\n  |> duplicate(column: \"_stop\", as: \"_time\")\n  |> drop(columns: [\"_measurement\"])\n  |> keep(columns: [\"_value\", \"_time\", \"cc\", \"country\", \"region\"])\n  ////|> aggregateWindow(every: 1h, fn: last)\n\n\nj = join(\n\ttables: {t1: src, t2: co2eqkwh},\n    on: [\"cc\", \"_time\"],\n\t)\n    |> map(fn: (r) => ({\n    r with\n    \t//system_power_input: r._value_t1,\n    \t//carbonIntensity: r._value_t2,\n    \tregion: r.region_t1,\n    \tcountry: r.country_t1,\n      _value: float(v: r._value_t1) * float(v: r._value_t2) / 1000.0,\n    \t//_time: r._time_t1\n\t}))\n    |> keep(columns: [\"_value\", \"_time\",\"source\"])\n    |> yield()"
    }
   ]
  },
  { "title": "Last 1w", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Last 7 days",
   "type": "bargauge",
   "description": "At 1AM of next day shows the total of the previous day. Last value (for incomplete time window) is shown in the legend.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "massg" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"dict\"\nimport \"date\" //import library to add date functions\n\nmonths = [1:\"January\",2:\"February\",3:\"March\",4:\"April\",5:\"May\",6:\"June\",7:\"July\",8:\"August\",9:\"September\",10:\"October\",11:\"November\",12: \"December\"]\ndays = [0:\"Sunday\", 1:\"Monday\", 2:\"Tuesday\", 3:\"Wednesday\", 4:\"Thursday\",5:\"Friday\", 6:\"Saturday\"]\ntimeIntervalkWh = 1h\ntimeInterval = 1d\ntimeRange = 8d\n\nsrc = from(bucket: \"bucket1\")\n  //|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> range(start: -timeRange)\n  |> filter(fn: (r) =>\n  r._measurement == \"Cisco-IOS-XR-sysadmin-fretta-envmon-ui:environment/oper/power/location/pem_attributes\" and\n  r._field == \"system_power_input\" and r.source != \"Ravello-51\")\n  |> window(every: timeIntervalkWh)\n  |> mean()\n  |> duplicate(column: \"_start\", as: \"_time\")\n\nco2eqkwh = from(bucket: \"bucket1\")\n  //|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> range(start: -timeRange)\n  |> filter(fn: (r) =>\n  \t  r._measurement == \"electricity-map\" and\n      r._field == \"carbonIntensity\")\n  |> window(every: timeIntervalkWh)\n  |> mean()\n  |> duplicate(column: \"_start\", as: \"_time\")\n  |> drop(columns: [\"_measurement\"])\n  |> keep(columns: [\"_value\", \"_time\", \"cc\", \"country\", \"region\"])\n\nj = join(\n\ttables: {t1: src, t2: co2eqkwh},\n    on: [\"cc\", \"_time\"],\n\t)\n    |> map(fn: (r) => ({\n    r with\n    \tregion: r.region_t1,\n    \tcountry: r.country_t1,\n      _value: float(v: r._value_t1) * float(v: r._value_t2) / 1000.0,\n\t}))\n    |> keep(columns: [\"_value\", \"_time\",\"source\"])\n    |> group()\n    |> aggregateWindow(every: timeInterval, fn: sum)\n    |> keep(columns: [\"_value\", \"_time\"])\n\t|> timeShift(duration: -2h) // Influx calculates the previous day and sets the value to the next day at 1AM. Here, we want to go back 2hrs to be able to have the correct day name. Therefore, subtract by 2h (=> 23:00 of previous day will be the timestamp).\n    |> map(fn: (r) => ({ r with //Valuemapping of weeknumber to weekname\n      namedDay: dict.get(dict: days, key:date.weekDay(t: r._time), default: \"\")\n    }))\n  \t|> keep(columns: [\"_value\", \"source\", \"namedDay\", \"_time\"])\n  \t|> group(columns: [\"_time\", \"namedDay\"])\n  \t|> truncateTimeColumn(unit: 1d)\n  \t|> group()\n    ///|> keep(columns: [\"namedDay\", \"_value\"])\n    ///|> group(columns: [\"namedDay\"])\n    ///|> sum()\n  \t///|> group()\n  \t|> range(start: -timeRange, stop: now()) // recalibrate the range\n    |> keep(columns: [\"_time\", \"_value\", \"namedDay\"])\n    |> pivot(rowKey: [], columnKey: [\"namedDay\", \"_time\"], valueColumn: \"_value\") //formatting for Grafana\n\t|> yield()"
    }
   ]
  },
  { "title": "Last 1mo", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Last 1 mo",
   "type": "bargauge",
   "description": "Month-wise: At 1AM of next day shows the total of the previous year. Last value (for incomplete time window) is shown in the legend. See: https://docs.influxdata.com/flux/v0.x/stdlib/universe/aggregatewindow/#calendar-months-and-years",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "massg" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"dict\"\nimport \"date\" //import library to add date functions\n\n//days = [0:\"Sunday\", 1:\"Monday\", 2:\"Tuesday\", 3:\"Wednesday\", 4:\"Thursday\",5:\"Friday\", 6:\"Saturday\"]\nmonths = [1:\"January\",2:\"February\",3:\"March\",4:\"April\",5:\"May\",6:\"June\",7:\"July\",8:\"August\",9:\"September\",10:\"October\",11:\"November\",12: \"December\"]\n\ntimeIntervalkWh = 1h\ntimeInterval = 1w\ntimeRange = 1mo\n\nsrc = from(bucket: \"bucket1\")\n  //|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> range(start: -timeRange)\n  |> filter(fn: (r) =>\n    r._measurement == \"Cisco-IOS-XR-sysadmin-fretta-envmon-ui:environment/oper/power/location/pem_attributes\" and\n    r._field == \"system_power_input\" and r.source != \"Ravello-51\")\n  //|> aggregateWindow(every: 1h, fn: mean)\n  //|> keep(columns: [\"_value\", \"_time\",\"source\"])\n  |> window(every: timeIntervalkWh)\n  |> mean()\n  |> duplicate(column: \"_start\", as: \"_time\")\n  |> keep(columns: [\"_value\", \"_time\",\"source\", \"cc\", \"country\", \"region\", \"measurement\"])\n  \n\nco2eqkwh = from(bucket: \"bucket1\")\n  //|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> range(start: -timeRange)\n  |> filter(fn: (r) =>\n    r._measurement == \"electricity-map\" and\n    r._field == \"carbonIntensity\")\n  //|> drop(columns: [\"_measurement\", \"_start\", \"_stop\"])\n  |> window(every: timeIntervalkWh)\n  |> mean()\n  |> duplicate(column: \"_start\", as: \"_time\")\n  |> drop(columns: [\"_measurement\"])\n  |> keep(columns: [\"_value\", \"_time\", \"cc\", \"country\", \"region\"])\n  //|> aggregateWindow(every: 1h, fn: last)\n\n\nj = join(\n\ttables: {t1: src, t2: co2eqkwh},\n    on: [\"cc\", \"_time\"],\n\t)\n  |> map(fn: (r) => ({\n    r with\n      //system_power_input: r._value_t1,\n      //carbonIntensity: r._value_t2,\n      region: r.region_t1,\n      country: r.country_t1,\n      _value: float(v: r._value_t1) * float(v: r._value_t2) / 1000.0,\n      //_time: r._time_t1\n  }))\n  |> keep(columns: [\"_value\", \"_time\",\"source\"])\n  //|> aggregateWindow(every: 1h, fn: mean)\n  //|> keep(columns: [\"_value\", \"_time\"])\n  |> group()\n  |> aggregateWindow(every: timeInterval, fn: sum)\n  //|> window(every: 30d)\n  //|> sum()\n  //|> duplicate(column: \"_start\", as: \"_time\")\n  //|> keep(columns: [\"_value\", \"_time\",\"source\"])\n  |> map(fn: (r) => ({\n    r with //Valuemapping of weeknumber\n    namedweek: date.week(t: r._time)\n  })) \n  |> keep(columns: [\"_value\", \"source\", \"namedweek\"])\n  |> group(columns: [\"namedweek\"])\n  |> group()\n  |> pivot(rowKey: [], columnKey: [\"namedweek\"], valueColumn: \"_value\") //formatting for Grafana\n  |> yield()"
    }
   ]
  },
  { "title": "Last 1y", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Last 1 year",
   "type": "bargauge",
   "description": "Month-wise: At 1AM of next day shows the total of the previous year. Last value (for incomplete time window) is shown in the legend. See: https://docs.influxdata.com/flux/v0.x/stdlib/universe/aggregatewindow/#calendar-months-and-years",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "massg" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"dict\"\nimport \"date\" //import library to add date functions\n\n//days = [0:\"Sunday\", 1:\"Monday\", 2:\"Tuesday\", 3:\"Wednesday\", 4:\"Thursday\",5:\"Friday\", 6:\"Saturday\"]\nmonths = [1:\"January\",2:\"February\",3:\"March\",4:\"April\",5:\"May\",6:\"June\",7:\"July\",8:\"August\",9:\"September\",10:\"October\",11:\"November\",12: \"December\"]\n\ntimeIntervalkWh = 6h\ntimeInterval = 30d\ntimeRange = 1y\n\nsrc = from(bucket: \"bucket1\")\n  //|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> range(start: -timeRange)\n  |> filter(fn: (r) =>\n    r._measurement == \"Cisco-IOS-XR-sysadmin-fretta-envmon-ui:environment/oper/power/location/pem_attributes\" and\n    r._field == \"system_power_input\" and r.source != \"Ravello-51\")\n  //|> aggregateWindow(every: 1h, fn: mean)\n  //|> keep(columns: [\"_value\", \"_time\",\"source\"])\n  |> window(every: timeIntervalkWh)\n  |> mean()\n  |> duplicate(column: \"_start\", as: \"_time\")\n  |> keep(columns: [\"_value\", \"_time\",\"source\", \"cc\", \"country\", \"region\", \"measurement\"])\n  \n\nco2eqkwh = from(bucket: \"bucket1\")\n  //|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> range(start: -timeRange)\n  |> filter(fn: (r) =>\n    r._measurement == \"electricity-map\" and\n    r._field == \"carbonIntensity\")\n  //|> drop(columns: [\"_measurement\", \"_start\", \"_stop\"])\n  |> window(every: timeIntervalkWh)\n  |> mean()\n  |> duplicate(column: \"_start\", as: \"_time\")\n  |> drop(columns: [\"_measurement\"])\n  |> keep(columns: [\"_value\", \"_time\", \"cc\", \"country\", \"region\"])\n  //|> aggregateWindow(every: 1h, fn: last)\n\n\nj = join(\n\ttables: {t1: src, t2: co2eqkwh},\n    on: [\"cc\", \"_time\"],\n\t)\n  |> map(fn: (r) => ({\n    r with\n      //system_power_input: r._value_t1,\n      //carbonIntensity: r._value_t2,\n      region: r.region_t1,\n      country: r.country_t1,\n      _value: float(v: r._value_t1) * 6.0 * float(v: r._value_t2) / 1000.0,\n      //_time: r._time_t1\n  }))\n  |> keep(columns: [\"_value\", \"_time\",\"source\"])\n  //|> aggregateWindow(every: 1h, fn: mean)\n  //|> keep(columns: [\"_value\", \"_time\"])\n  |> group()\n  |> aggregateWindow(every: timeInterval, fn: sum)\n  //|> window(every: 30d)\n  //|> sum()\n  //|> duplicate(column: \"_start\", as: \"_time\")\n  //|> keep(columns: [\"_value\", \"_time\",\"source\"])\n  |> map(fn: (r) => ({\n    r with //Valuemapping of monthnumber to monthname\n    namedMonth: dict.get(dict: months, key:date.month(t: r._time), default: \"\")\n  })) \n  |> keep(columns: [\"_value\", \"source\", \"namedMonth\"])\n  |> group(columns: [\"namedMonth\"])\n  |> group()\n  |> pivot(rowKey: [], columnKey: [\"namedMonth\"], valueColumn: \"_value\") //formatting for Grafana\n  |> yield()"
    }
   ]
  }
 ]
}