{
 "title": "Overview with CO2",
 "description": "Overview of power consumption for RON lab and others",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "ncs_host",
    "label": "NCS host",
    "query": "import \"influxdata/influxdb/v1\"\n\nv1.measurementTagValues(\n  bucket: \"bucket1\",\n  measurement: \"Cisco-IOS-XR-sysadmin-fretta-envmon-ui:environment/oper/power/location/pem_attributes\",\n  tag: \"source\"\n)"
   },
   {
    "name": "asr9k_host",
    "label": "ASR 9K host",
    "query": "import \"influxdata/influxdb/v1\"\n\nv1.measurementTagValues(\n  bucket: \"bucket1\",\n  measurement: \"Cisco-IOS-XR-sysadmin-asr9k-envmon-ui:environment/oper/power/location/pem_attributes\",\n  tag: \"source\"\n)"
   },
   {
    "name": "8k_host",
    "label": "Cisco Router 8201 host",
    "query": "import \"influxdata/influxdb/v1\"\n\nv1.measurementTagValues(\n  bucket: \"bucket1\",\n  measurement: \"Cisco-IOS-XR-invmgr-oper:inventory/entities/entity/attributes/env-sensor-info\",\n  tag: \"source\"\n)"
   }
  ]
 },
 "panels": [
  {
   "title": "Nexus 3K",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Input power",
     "type": "bargauge",
     "gridPos": { "h": 5, "w": 13, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"bucket1\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => \n  \tr._measurement == \"show environment power\" and\n    (\n    r._field == \"powersup/power_summary/tot_pow_input_actual_draw\" and\n    (r.source =~ /r25-eu-spdc/) // Get only the 92xx\n    )\n    )\n  |> keep(columns: [\"_field\", \"_value\", \"_time\", \"source\"])\n  |> group()\n  |> sort(columns: [\"_time\"], desc: true)\n  |> unique(column: \"source\")\n  |> sort(columns: [\"source\"], desc: true)\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"source\"], valueColumn: \"_value\")"
      }
     ]
    },
    {
     "title": "Required power",
     "type": "stat",
     "gridPos": { "h": 5, "w": 2, "x": 13, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"bucket1\")\n  |> range(start: v.timeRangeStart)\n  |> filter(fn: (r) => \n  \tr._measurement == \"show environment power\" and\n    (\n    r._field == \"powersup/power_summary/tot_pow_capacity\" and\n    (r.source =~ /r25-eu-spdc/) // Get only the 92xx\n    ))\n  |> keep(columns: [\"_field\", \"_value\", \"_time\", \"source\"])\n  |> group()\n  |> sort(columns: [\"_time\"], desc: true)\n  |> unique(column: \"source\")\n  |> sort(columns: [\"source\"], desc: true)\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"source\"], valueColumn: \"_value\")"
      }
     ]
    },
    {
     "title": "Regional C emissions [g CO2 eq / kWh]",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 4, "x": 16, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "massg" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "src = from(bucket: \"bucket1\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n  r._measurement == \"show environment power\" and\n  r._field == \"powersup/power_summary/tot_pow_input_actual_draw\" and\n    (r.source =~ /r25-eu-spdc/) // Get only the 92xx\n    )\n  |> window(every: 5m)\n  |> mean()\n  |> duplicate(column: \"_stop\", as: \"_time\")\n  |> drop(columns: [\"_stop\", \"_start\"])\n\nco2eqkwh = from(bucket: \"bucket1\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n  \t  r._measurement == \"electricity-map\" and\n      r._field == \"carbonIntensity\")\n  |> drop(columns: [\"_measurement\"])\n  |> window(every: 5m)\n  |> mean()\n  |> duplicate(column: \"_stop\", as: \"_time\")\n  |> drop(columns: [\"_stop\", \"_start\"])\n\nj = join(\n\ttables: {t1: src, t2: co2eqkwh},\n    on: [\"cc\", \"_time\"],\n\t)\n    |> map(fn: (r) => ({\n    r with\n    \tregion: r.region_t1,\n    \tcountry: r.country_t1,\n      _value: r._value_t2,\n\t}))\n  |> keep(columns: [\"_value\", \"_time\", \"cc\", \"source\", \"subscription\", \"_measurement\"])\n  |> group()\n  |> sort(columns: [\"_time\"], desc: true)\n  |> unique(column: \"source\")\n  |> sort(columns: [\"source\"], desc: true)\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"source\", \"cc\"], valueColumn: \"_value\")\n \t|> yield()"
      }
     ]
    },
    {
     "title": "Current C emissions / h [g CO2 eq / h]",
     "type": "stat",
     "description": "//Carbon emission (extrapolated to 1h)\n\n//Gives us the carbon emissions per hour (W x gCO₂eq/kWh = (J/s) x gCO2eq / kWh = (J/s) x gCO2eq / (1000Wh) = (J/s) x gCO2eq / (3600x1000J) = JxgCO2eq/(3600sx1000J) = gCO2eq/(3600sx1000) = gCO2eq/1000h)",
     "gridPos": { "h": 5, "w": 2, "x": 20, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "massg" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "//Carbon emission (extrapolated to 1h)\n\n//Gives us the carbon emissions per hour (W x gCO₂eq/kWh = (J/s) x gCO2eq / kWh = (J/s) x gCO2eq / (1000Wh) = (J/s) x gCO2eq / (3600x1000J) = JxgCO2eq/(3600sx1000J) = gCO2eq/(3600sx1000) = gCO2eq/1000h)\n\nsrc = from(bucket: \"bucket1\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n  r._measurement == \"show environment power\" and\n  r._field == \"powersup/power_summary/tot_pow_input_actual_draw\" and\n    (r.source =~ /r25-eu-spdc/) // Get only the 92xx\n    )\n  |> window(every: 5m)\n  |> mean()\n  |> duplicate(column: \"_stop\", as: \"_time\")\n  |> drop(columns: [\"_stop\", \"_start\"])\n\nco2eqkwh = from(bucket: \"bucket1\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n  \t  r._measurement == \"electricity-map\" and\n      r._field == \"carbonIntensity\")\n  |> drop(columns: [\"_measurement\"])\n  |> window(every: 5m)\n  |> mean()\n  |> duplicate(column: \"_stop\", as: \"_time\")\n  |> drop(columns: [\"_stop\", \"_start\"])\n\nj = join(\n\ttables: {t1: src, t2: co2eqkwh},\n    on: [\"cc\", \"_time\"],\n\t)\n    |> map(fn: (r) => ({\n    r with\n    \tregion: r.region_t1,\n    \tcountry: r.country_t1,\n      _value: float(v: r._value_t1) * float(v: r._value_t2) / 1000.0,\n\t}))\n    |> keep(columns: [\"_value\", \"_time\", \"cc\", \"source\", \"subscription\", \"_measurement\"])\n    // For sorting data (replaces |>last())\n    |> group()\n    |> sort(columns: [\"_time\"], desc: true)\n    |> unique(column: \"source\")\n    |> sort(columns: [\"source\"], desc: true)\n    |> pivot(rowKey:[\"_time\"], columnKey: [\"source\", \"cc\"], valueColumn: \"_value\")\n  \t|> yield()"
      }
     ]
    }
   ]
  },
  {
   "title": "Nexus 92xx",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Input power",
     "type": "bargauge",
     "gridPos": { "h": 7, "w": 13, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"bucket1\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => \n  \tr._measurement == \"show environment power\" and\n    (\n    r._field == \"powersup/power_summary/tot_pow_input_actual_draw\" and\n    (r.source =~ /r[0-9][2-4]-eu-spdc/) // Get only the 92xx\n    )\n    )\n  |> keep(columns: [\"_field\", \"_value\", \"_time\", \"source\"])\n  |> group()\n  |> sort(columns: [\"_time\"], desc: true)\n  |> unique(column: \"source\")\n  |> sort(columns: [\"source\"], desc: true)\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"source\"], valueColumn: \"_value\")"
      }
     ]
    },
    {
     "title": "Required power",
     "type": "stat",
     "gridPos": { "h": 7, "w": 2, "x": 13, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"bucket1\")\n  |> range(start: v.timeRangeStart)\n  |> filter(fn: (r) => \n  \tr._measurement == \"show environment power\" and\n    (\n    r._field == \"powersup/power_summary/tot_pow_capacity\" and\n    (r.source =~ /r[0-9][2-4]-eu-spdc/) // Get only the 92xx\n    ))\n  |> keep(columns: [\"_field\", \"_value\", \"_time\", \"source\"])\n  |> group()\n  |> sort(columns: [\"_time\"], desc: true)\n  |> unique(column: \"source\")\n  |> sort(columns: [\"source\"], desc: true)\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"source\"], valueColumn: \"_value\")"
      }
     ]
    },
    {
     "title": "Regional C emissions [g CO2 eq / kWh]",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 4, "x": 16, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "massg" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "src = from(bucket: \"bucket1\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n  r._measurement == \"show environment power\" and\n  r._field == \"powersup/power_summary/tot_pow_input_actual_draw\" and\n    (r.source =~ /r[0-9][2-4]-eu-spdc/) // Get only the 92xx\n    )\n  |> window(every: 5m)\n  |> mean()\n  |> duplicate(column: \"_stop\", as: \"_time\")\n  |> drop(columns: [\"_stop\", \"_start\"])\n\nco2eqkwh = from(bucket: \"bucket1\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n  \t  r._measurement == \"electricity-map\" and\n      r._field == \"carbonIntensity\")\n  |> drop(columns: [\"_measurement\"])\n  |> window(every: 5m)\n  |> mean()\n  |> duplicate(column: \"_stop\", as: \"_time\")\n  |> drop(columns: [\"_stop\", \"_start\"])\n\nj = join(\n\ttables: {t1: src, t2: co2eqkwh},\n    on: [\"cc\", \"_time\"],\n\t)\n    |> map(fn: (r) => ({\n    r with\n    \tregion: r.region_t1,\n    \tcountry: r.country_t1,\n      _value: r._value_t2,\n\t}))\n    |> keep(columns: [\"_value\", \"_time\", \"cc\", \"source\", \"subscription\", \"_measurement\"])\n  |> group()\n  |> sort(columns: [\"_time\"], desc: true)\n  |> unique(column: \"source\")\n  |> sort(columns: [\"source\"], desc: true)\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"source\", \"cc\"], valueColumn: \"_value\")\n \t|> yield()"
      }
     ]
    },
    {
     "title": "Current C emissions / h [g CO2 eq / h]",
     "type": "stat",
     "description": "//Carbon emission (extrapolated to 1h)\n\n//Gives us the carbon emissions per hour (W x gCO₂eq/kWh = (J/s) x gCO2eq / kWh = (J/s) x gCO2eq / (1000Wh) = (J/s) x gCO2eq / (3600x1000J) = JxgCO2eq/(3600sx1000J) = gCO2eq/(3600sx1000) = gCO2eq/1000h)",
     "gridPos": { "h": 7, "w": 2, "x": 20, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "massg" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "//Carbon emission (extrapolated to 1h)\n\n//Gives us the carbon emissions per hour (W x gCO₂eq/kWh = (J/s) x gCO2eq / kWh = (J/s) x gCO2eq / (1000Wh) = (J/s) x gCO2eq / (3600x1000J) = JxgCO2eq/(3600sx1000J) = gCO2eq/(3600sx1000) = gCO2eq/1000h)\n\nsrc = from(bucket: \"bucket1\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n  r._measurement == \"show environment power\" and\n  r._field == \"powersup/power_summary/tot_pow_input_actual_draw\" and\n    (r.source =~ /r[0-9][2-4]-eu-spdc/) // Get only the 92xx\n    )\n  |> window(every: 5m)\n  |> mean()\n  |> duplicate(column: \"_stop\", as: \"_time\")\n  |> drop(columns: [\"_stop\", \"_start\"])\n\nco2eqkwh = from(bucket: \"bucket1\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n  \t  r._measurement == \"electricity-map\" and\n      r._field == \"carbonIntensity\")\n  |> drop(columns: [\"_measurement\"])\n  |> window(every: 5m)\n  |> mean()\n  |> duplicate(column: \"_stop\", as: \"_time\")\n  |> drop(columns: [\"_stop\", \"_start\"])\n\nj = join(\n\ttables: {t1: src, t2: co2eqkwh},\n    on: [\"cc\", \"_time\"],\n\t)\n    |> map(fn: (r) => ({\n    r with\n    \tregion: r.region_t1,\n    \tcountry: r.country_t1,\n      _value: float(v: r._value_t1) * float(v: r._value_t2) / 1000.0,\n\t}))\n    |> keep(columns: [\"_value\", \"_time\", \"cc\", \"source\", \"subscription\", \"_measurement\"])\n    // For sorting data (replaces |>last())\n    |> group()\n    |> sort(columns: [\"_time\"], desc: true)\n    |> unique(column: \"source\")\n    |> sort(columns: [\"source\"], desc: true)\n    |> pivot(rowKey:[\"_time\"], columnKey: [\"source\", \"cc\"], valueColumn: \"_value\")\n  \t|> yield()\n    // Gives us the carbon emissions per second (W x gCO₂eq/kWh = (J/s) x gCO2eq / kWh = (J/s) x gCO2eq / (1000Wh) = (J/s) x gCO2eq / 1000J = gCO2eq/1000s)"
      }
     ]
    }
   ]
  },
  { "title": "Nexus 93xx", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Input power",
   "type": "bargauge",
   "gridPos": { "h": 23, "w": 13, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"bucket1\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => \n  \tr._measurement == \"show environment power\" and\n    (\n    r._field == \"powersup/power_summary/tot_pow_input_actual_draw\" and\n    (r.source =~ /rs1-core.*/ or r.source =~ /rs[0-9]-mgm-tor/ or r.source == \"Yavin-129\" or r.source =~ /rs[0-9]-mgm-mor/ or r.source =~ /ipn[0-9][0-9]-eu-spdc/ or r.source == \"Tatooine-136\" or r.source =~ /rl[0-9][0-9][0-9]-eu-spdc/ or r.source =~ /cl[0-9][0-9][0-9]-eu-spdc/) //Get only the 93xx\n    )\n    )\n  |> keep(columns: [\"_field\", \"_value\", \"_time\", \"source\"])\n  |> group()\n  |> sort(columns: [\"_time\"], desc: true)\n  |> unique(column: \"source\")\n  |> sort(columns: [\"source\"], desc: true)\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"source\"], valueColumn: \"_value\")"
    },
    {
     "query": "from(bucket: \"bucket1\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"apic-switch\")\n  |> filter(fn: (r) => r[\"_field\"] == \"pIn\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> group(columns: [\"_time\", \"name\"])\n  |> keep(columns: [\"pIn\", \"name\", \"_time\"])\n  |> sum(column: \"pIn\")\n  |> group(columns: [\"name\"])\n  |> last(column: \"pIn\")\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"name\"], valueColumn: \"pIn\")"
    }
   ]
  },
  {
   "title": "Required power",
   "type": "stat",
   "gridPos": { "h": 23, "w": 2, "x": 13, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"bucket1\")\n  |> range(start: v.timeRangeStart)\n  |> filter(fn: (r) => \n  \tr._measurement == \"show environment power\" and\n    (\n    r._field == \"powersup/power_summary/tot_pow_capacity\" and\n    (r.source == \"Yavin-129\" or r.source =~ /rs1-core.*/ or r.source =~ /rs[0-9]-mgm-tor/ or r.source =~ /rs[0-9]-mgm-mor/ or r.source =~ /ipn[0-9][0-9]-eu-spdc/ or r.source == \"Tatooine-136\" or r.source =~ /rl[0-9][0-9][0-9]-eu-spdc/ or r.source =~ /cl[0-9][0-9][0-9]-eu-spdc/) // Get only the 93xx\n    ))\n  |> keep(columns: [\"_field\", \"_value\", \"_time\", \"source\"])\n  |> group()\n  |> sort(columns: [\"_time\"], desc: true)\n  |> unique(column: \"source\")\n  |> sort(columns: [\"source\"], desc: true)\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"source\"], valueColumn: \"_value\")"
    }
   ]
  },
  {
   "title": "Regional C emissions [g CO2 eq / kWh]",
   "type": "gauge",
   "gridPos": { "h": 23, "w": 4, "x": 16, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "massg" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "src = from(bucket: \"bucket1\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n  r._measurement == \"show environment power\" and\n  r._field == \"powersup/power_summary/tot_pow_input_actual_draw\"  and\n    (r.source =~ /rs1-core.*/ or r.source =~ /rs[0-9]-mgm-tor/ or r.source =~ /rs[0-9]-mgm-mor/ or r.source =~ /ipn[0-9][0-9]-eu-spdc/ or r.source == \"Tatooine-136\" or r.source == \"Tatooine-136\" or r.source =~ /rl[0-9][0-9][0-9]-eu-spdc/ or r.source =~ /cl[0-9][0-9][0-9]-eu-spdc/) // Get only the 93xx\n    )\n  |> window(every: 5m)\n  |> mean()\n  |> duplicate(column: \"_stop\", as: \"_time\")\n  |> drop(columns: [\"_stop\", \"_start\"])\n\nco2eqkwh = from(bucket: \"bucket1\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n  \t  r._measurement == \"electricity-map\" and\n      r._field == \"carbonIntensity\")\n  |> drop(columns: [\"_measurement\"])\n  |> window(every: 5m)\n  |> mean()\n  |> duplicate(column: \"_stop\", as: \"_time\")\n  |> drop(columns: [\"_stop\", \"_start\"])\n\nj = join(\n\ttables: {t1: src, t2: co2eqkwh},\n    on: [\"cc\", \"_time\"],\n\t)\n    |> map(fn: (r) => ({\n    r with\n    \tregion: r.region_t1,\n    \tcountry: r.country_t1,\n      _value: r._value_t2,\n\t}))\n    |> keep(columns: [\"_value\", \"_time\", \"cc\", \"source\", \"subscription\", \"_measurement\"])  \n    |> group()\n    |> sort(columns: [\"_time\"], desc: true)\n    |> unique(column: \"source\")\n    |> sort(columns: [\"source\"], desc: true)\n    |> pivot(rowKey:[\"_time\"], columnKey: [\"source\", \"cc\"], valueColumn: \"_value\")\n \t|> yield()\n\n"
    },
    {
     "query": "src = from(bucket: \"bucket1\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"apic-switch\")\n  |> filter(fn: (r) => r[\"_field\"] == \"pIn\")\n  |> window(every: 5m)\n  |> mean()\n  |> duplicate(column: \"_stop\", as: \"_time\")\n  |> drop(columns: [\"_stop\", \"_start\"])\n\nco2eqkwh = from(bucket: \"bucket1\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n  \t  r._measurement == \"electricity-map\" and\n      r._field == \"carbonIntensity\")\n  |> drop(columns: [\"_measurement\"])\n  |> window(every: 5m)\n  |> mean()\n  |> duplicate(column: \"_stop\", as: \"_time\")\n  |> drop(columns: [\"_stop\", \"_start\"])\n\nj = join(\n\ttables: {t1: src, t2: co2eqkwh},\n    on: [\"cc\", \"_time\"],\n\t)\n  |> map(fn: (r) => ({\n  r with\n    region: r.region_t1,\n    country: r.country_t1,\n    _value: r._value_t2,\n}))\n  |> keep(columns: [\"_value\", \"_time\", \"cc\", \"name\", \"subscription\", \"_measurement\"])\n  |> group()\n  |> sort(columns: [\"_time\"], desc: true)\n  |> unique(column: \"name\")\n  |> sort(columns: [\"name\"], desc: true)\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"name\", \"cc\"], valueColumn: \"_value\")\n \t|> yield()"
    }
   ]
  },
  {
   "title": "Current C emissions / h [g CO2 eq / h]",
   "type": "stat",
   "description": "//Carbon emission (extrapolated to 1h)\n\n//Gives us the carbon emissions per hour (W x gCO₂eq/kWh = (J/s) x gCO2eq / kWh = (J/s) x gCO2eq / (1000Wh) = (J/s) x gCO2eq / (3600x1000J) = JxgCO2eq/(3600sx1000J) = gCO2eq/(3600sx1000) = gCO2eq/1000h)",
   "gridPos": { "h": 23, "w": 2, "x": 20, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "massg" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "//Carbon emission (extrapolated to 1h)\n\n//Gives us the carbon emissions per hour (W x gCO₂eq/kWh = (J/s) x gCO2eq / kWh = (J/s) x gCO2eq / (1000Wh) = (J/s) x gCO2eq / (3600x1000J) = JxgCO2eq/(3600sx1000J) = gCO2eq/(3600sx1000) = gCO2eq/1000h)\n\nsrc = from(bucket: \"bucket1\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n  r._measurement == \"show environment power\" and\n  r._field == \"powersup/power_summary/tot_pow_input_actual_draw\" and\n    (r.source =~ /rs1-core.*/ or r.source =~ /rs[0-9]-mgm-tor/ or r.source =~ /rs[0-9]-mgm-mor/ or r.source =~ /ipn[0-9][0-9]-eu-spdc/ or r.source == \"Tatooine-136\" or r.source =~ /rl[0-9][0-9][0-9]-eu-spdc/ or r.source =~ /cl[0-9][0-9][0-9]-eu-spdc/) // Get only the 93xx\n    )\n  |> window(every: 5m)\n  |> mean()\n  |> duplicate(column: \"_stop\", as: \"_time\")\n  |> drop(columns: [\"_stop\", \"_start\"])\n\nco2eqkwh = from(bucket: \"bucket1\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n  \t  r._measurement == \"electricity-map\" and\n      r._field == \"carbonIntensity\")\n  |> drop(columns: [\"_measurement\"])\n  |> window(every: 5m)\n  |> mean()\n  |> duplicate(column: \"_stop\", as: \"_time\")\n  |> drop(columns: [\"_stop\", \"_start\"])\n\nj = join(\n\ttables: {t1: src, t2: co2eqkwh},\n    on: [\"cc\", \"_time\"],\n\t)\n    |> map(fn: (r) => ({\n    r with\n    \t//system_power_input: r._value_t1,\n    \t//carbonIntensity: r._value_t2,\n    \tregion: r.region_t1,\n    \tcountry: r.country_t1,\n      _value: float(v: r._value_t1) * float(v: r._value_t2) / 1000.0,\n\t}))\n    |> keep(columns: [\"_value\", \"_time\", \"cc\", \"source\", \"subscription\", \"_measurement\"])\n    // For sorting data (replaces |>last())\n    |> group()\n    |> sort(columns: [\"_time\"], desc: true)\n    |> unique(column: \"source\")\n    |> sort(columns: [\"source\"], desc: true)\n    |> pivot(rowKey:[\"_time\"], columnKey: [\"source\", \"cc\"], valueColumn: \"_value\")\n  \t|> yield()"
    },
    {
     "query": "//Carbon emission (extrapolated to 1h)\n\n//Gives us the carbon emissions per hour (W x gCO₂eq/kWh = (J/s) x gCO2eq / kWh = (J/s) x gCO2eq / (1000Wh) = (J/s) x gCO2eq / (3600x1000J) = JxgCO2eq/(3600sx1000J) = gCO2eq/(3600sx1000) = gCO2eq/1000h)\n\nsrc = from(bucket: \"bucket1\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"apic-switch\")\n  |> filter(fn: (r) => r[\"_field\"] == \"pIn\")\n  |> window(every: 5m)\n  |> mean()\n  |> duplicate(column: \"_stop\", as: \"_time\")\n  |> drop(columns: [\"_stop\", \"_start\"])\n\nco2eqkwh = from(bucket: \"bucket1\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n  \t  r._measurement == \"electricity-map\" and\n      r._field == \"carbonIntensity\")\n  |> drop(columns: [\"_measurement\"])\n  |> window(every: 5m)\n  |> mean()\n  |> duplicate(column: \"_stop\", as: \"_time\")\n  |> drop(columns: [\"_stop\", \"_start\"])\n\nj = join(\n\ttables: {t1: src, t2: co2eqkwh},\n    on: [\"cc\", \"_time\"],\n\t)\n    |> map(fn: (r) => ({\n    r with\n    \tregion: r.region_t1,\n    \tcountry: r.country_t1,\n      _value: float(v: r._value_t1) * float(v: r._value_t2) / 1000.0,\n\t}))\n    |> keep(columns: [\"_value\", \"_time\", \"cc\", \"name\", \"subscription\", \"_measurement\"])\n    // For sorting data (replaces |>last())\n    |> group()\n    |> sort(columns: [\"_time\"], desc: true)\n    |> unique(column: \"name\")\n    |> sort(columns: [\"name\"], desc: true)\n    |> pivot(rowKey:[\"_time\"], columnKey: [\"name\", \"cc\"], valueColumn: \"_value\")\n  \t|> yield()"
    }
   ]
  },
  {
   "title": "NCS5xx",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Input power",
     "type": "bargauge",
     "gridPos": { "h": 5, "w": 13, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"bucket1\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => \n  \tr._measurement == \"Cisco-IOS-XR-sysadmin-fretta-envmon-ui:environment/oper/power/location/pem_attributes\" and \n    r.source == \"Lyon-23\" and\n    (\n    //r._field == \"usable_power_capacity\" or \n    //r._field == \"protection_power_capacity\" or\n    r._field == \"system_power_input\" //or \n    //r._field == \"system_power_used\"\n    )\n    )\n  //|> keep(columns: [\"_field\", \"_value\", \"_time\", \"pem\", \"location\", \"pem_id/value\", \"source\", \"confgd_power_redundancy_mode/value\"])\n  |> keep(columns: [\"_field\", \"_value\", \"_time\", \"source\"])\n  |> last()"
      }
     ]
    },
    {
     "title": "Required power",
     "type": "stat",
     "gridPos": { "h": 5, "w": 2, "x": 13, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"bucket1\")\n  |> range(start: v.timeRangeStart)\n  |> filter(fn: (r) => \n  \tr._measurement == \"Cisco-IOS-XR-sysadmin-fretta-envmon-ui:environment/oper/power/location/pem_attributes\" and \n    r.source == \"Lyon-23\" and\n    (\n    r._field == \"power_resrv_and_alloc\"\n    ))\n  //|> keep(columns: [\"_field\", \"_value\", \"_time\", \"pem\", \"location\", \"source\", \"pem_id/value\", \"confgd_power_redundancy_mode/value\"])\n  |> keep(columns: [\"_field\", \"_value\", \"_time\", \"source\"])\n  |> last()"
      }
     ]
    },
    {
     "title": "Regional C emissions [g CO2 eq / kWh]",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 4, "x": 16, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "massg" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "src = from(bucket: \"bucket1\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n  r._measurement == \"Cisco-IOS-XR-sysadmin-fretta-envmon-ui:environment/oper/power/location/pem_attributes\" and\n  r.source == \"Lyon-23\" and\n  r._field == \"system_power_input\")\n  |> window(every: 5m)\n  |> mean()\n  |> duplicate(column: \"_stop\", as: \"_time\")\n  |> drop(columns: [\"_stop\", \"_start\"])\n\nco2eqkwh = from(bucket: \"bucket1\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n  \t  r._measurement == \"electricity-map\" and\n      r._field == \"carbonIntensity\")\n  |> drop(columns: [\"_measurement\"])\n  |> window(every: 5m)\n  |> mean()\n  |> duplicate(column: \"_stop\", as: \"_time\")\n  |> drop(columns: [\"_stop\", \"_start\"])\n\nj = join(\n\ttables: {t1: src, t2: co2eqkwh},\n    on: [\"cc\", \"_time\"],\n\t)\n    |> map(fn: (r) => ({\n    r with\n    \tregion: r.region_t1,\n    \tcountry: r.country_t1,\n      _value: r._value_t2,\n\t}))\n    |> keep(columns: [\"_value\", \"_time\", \"cc\", \"source\", \"subscription\", \"_measurement\"])\n    |> last()\n  \t|> yield()"
      }
     ]
    },
    {
     "title": "Current C emissions / h [g CO2 eq / h]",
     "type": "stat",
     "description": "//Carbon emission (extrapolated to 1h)\n\n//Gives us the carbon emissions per hour (W x gCO₂eq/kWh = (J/s) x gCO2eq / kWh = (J/s) x gCO2eq / (1000Wh) = (J/s) x gCO2eq / (3600x1000J) = JxgCO2eq/(3600sx1000J) = gCO2eq/(3600sx1000) = gCO2eq/1000h)",
     "gridPos": { "h": 5, "w": 2, "x": 20, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "massg" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "//Carbon emission (extrapolated to 1h)\n\n//Gives us the carbon emissions per hour (W x gCO₂eq/kWh = (J/s) x gCO2eq / kWh = (J/s) x gCO2eq / (1000Wh) = (J/s) x gCO2eq / (3600x1000J) = JxgCO2eq/(3600sx1000J) = gCO2eq/(3600sx1000) = gCO2eq/1000h)\n\nsrc = from(bucket: \"bucket1\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n  r._measurement == \"Cisco-IOS-XR-sysadmin-fretta-envmon-ui:environment/oper/power/location/pem_attributes\" and\n  r.source == \"Lyon-23\" and\n  r._field == \"system_power_input\")\n  |> window(every: 5m)\n  |> mean()\n  |> duplicate(column: \"_stop\", as: \"_time\")\n  |> drop(columns: [\"_stop\", \"_start\"])\n\nco2eqkwh = from(bucket: \"bucket1\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n  \t  r._measurement == \"electricity-map\" and\n      r._field == \"carbonIntensity\")\n  |> drop(columns: [\"_measurement\"])\n  |> window(every: 5m)\n  |> mean()\n  |> duplicate(column: \"_stop\", as: \"_time\")\n  |> drop(columns: [\"_stop\", \"_start\"])\n\nj = join(\n\ttables: {t1: src, t2: co2eqkwh},\n    on: [\"cc\", \"_time\"],\n\t)\n    |> map(fn: (r) => ({\n    r with\n    \tregion: r.region_t1,\n    \tcountry: r.country_t1,\n      _value: float(v: r._value_t1) * float(v: r._value_t2) / 1000.0,\n\t}))\n    |> keep(columns: [\"_value\", \"_time\", \"cc\", \"source\", \"subscription\", \"_measurement\"])\n    |> last()\n  \t|> yield()"
      }
     ]
    }
   ]
  },
  {
   "title": "NCS5xxL",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "Input power",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 13, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"bucket1\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => \n    r.device_type != \"cisco-8k\" and\n  \tr._measurement == \"Cisco-IOS-XR-envmon-oper:power-management/rack/chassis\" and\n    r._field == \"total_pwr_output\"\n    )\n  |> keep(columns: [\"_field\", \"_value\", \"_time\", \"source\"])\n  |> map(fn: (r) => ({\n    r with\n    _value: (float(v: r._value) * 0.1 + float(v: r._value)) // Workaround: consider +10% of the output as input power\n   }))\n  |> group()\n  |> sort(columns: [\"_time\"], desc: true)\n  |> unique(column: \"source\")\n  |> sort(columns: [\"source\"], desc: true)\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"source\"], valueColumn: \"_value\")\n"
      }
     ]
    },
    {
     "title": "Required power",
     "type": "stat",
     "gridPos": { "h": 8, "w": 2, "x": 13, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"bucket1\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => \n    r.device_type != \"cisco-8k\" and\n    r._measurement == \"Cisco-IOS-XR-envmon-oper:power-management/rack/chassis\" and \n    (\n    //r._field == \"total_pwr_input\" or\n    //r._field == \"total_pwr_output\" or\n    //r._field == \"total_output_capacity\" or\n    r._field == \"total_pwr_required\"\n    )\n    )\n  //|> keep(columns: [\"_field\", \"_value\", \"_time\", \"name\", \"source\"])\n  |> keep(columns: [\"_field\", \"_value\", \"_time\", \"source\"])\n  // For sorting data (replaces |>last())\n  |> group()\n  |> sort(columns: [\"_time\"], desc: true)\n  |> unique(column: \"source\")\n  |> sort(columns: [\"source\"], desc: false)\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"source\"], valueColumn: \"_value\")"
      }
     ]
    },
    {
     "title": "Regional C emissions [g CO2 eq / kWh]",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 4, "x": 16, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "massg" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "src = from(bucket: \"bucket1\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => \n    r.device_type != \"cisco-8k\" and\n  \tr._measurement == \"Cisco-IOS-XR-envmon-oper:power-management/rack/chassis\" and\n    r._field == \"total_pwr_output\"\n    )\n  |> keep(columns: [\"_field\", \"_value\", \"_time\", \"source\", \"cc\"])\n  |> window(every: 5m)\n  |> mean()\n  |> duplicate(column: \"_stop\", as: \"_time\")\n  |> drop(columns: [\"_stop\", \"_start\"])\n\nco2eqkwh = from(bucket: \"bucket1\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n  \t  r._measurement == \"electricity-map\" and\n      r._field == \"carbonIntensity\")\n  |> drop(columns: [\"_measurement\"])\n  |> window(every: 5m)\n  |> mean()\n  |> duplicate(column: \"_stop\", as: \"_time\")\n  |> drop(columns: [\"_stop\", \"_start\"])\n\nj = join(\n\ttables: {t1: src, t2: co2eqkwh},\n    on: [\"cc\", \"_time\"],\n\t)\n    |> map(fn: (r) => ({\n    r with\n      _value: r._value_t2,\n\t}))\n    |> keep(columns: [\"_value\", \"_time\", \"cc\", \"source\", \"subscription\", \"_measurement\"])\n    \n    // For sorting data (replaces |>last())\n    |> group()\n    |> sort(columns: [\"_time\"], desc: true)\n    |> unique(column: \"source\")\n    |> sort(columns: [\"source\"], desc: false)\n    |> pivot(rowKey:[], columnKey: [\"source\", \"cc\"], valueColumn: \"_value\")\n  \t|> yield()\n    \n    "
      }
     ]
    },
    {
     "title": "Current C emissions / h [g CO2 eq / h]",
     "type": "stat",
     "description": "//Carbon emission (extrapolated to 1h)\n\n//Gives us the carbon emissions per hour (W x gCO₂eq/kWh = (J/s) x gCO2eq / kWh = (J/s) x gCO2eq / (1000Wh) = (J/s) x gCO2eq / (3600x1000J) = JxgCO2eq/(3600sx1000J) = gCO2eq/(3600sx1000) = gCO2eq/1000h)",
     "gridPos": { "h": 8, "w": 2, "x": 20, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "massg" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "//Carbon emission (extrapolated to 1h)\n\n//Gives us the carbon emissions per hour (W x gCO₂eq/kWh = (J/s) x gCO2eq / kWh = (J/s) x gCO2eq / (1000Wh) = (J/s) x gCO2eq / (3600x1000J) = JxgCO2eq/(3600sx1000J) = gCO2eq/(3600sx1000) = gCO2eq/1000h)\n\nsrc = from(bucket: \"bucket1\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => \n    r.device_type != \"cisco-8k\" and\n  \tr._measurement == \"Cisco-IOS-XR-envmon-oper:power-management/rack/chassis\" and\n    r._field == \"total_pwr_output\"\n    )\n  |> keep(columns: [\"_field\", \"_value\", \"_time\", \"source\", \"cc\"])\n  |> map(fn: (r) => ({\n    r with\n    _value: (float(v: r._value) * 0.1 + float(v: r._value)) // Workaround: consider +10% of the output as input power\n   }))\n  |> window(every: 5m)\n  |> mean()\n  |> duplicate(column: \"_stop\", as: \"_time\")\n  |> drop(columns: [\"_stop\", \"_start\"])\n\nco2eqkwh = from(bucket: \"bucket1\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n  \t  r._measurement == \"electricity-map\" and\n      r._field == \"carbonIntensity\")\n  |> drop(columns: [\"_measurement\"])\n  |> window(every: 5m)\n  |> mean()\n  |> duplicate(column: \"_stop\", as: \"_time\")\n  |> drop(columns: [\"_stop\", \"_start\"])\n\nj = join(\n\ttables: {t1: src, t2: co2eqkwh},\n    on: [\"cc\", \"_time\"],\n\t)\n    |> map(fn: (r) => ({\n    r with\n    \tregion: r.region_t1,\n    \tcountry: r.country_t1,\n      _value: float(v: r._value_t1) * float(v: r._value_t2) / 1000.0,\n\t}))\n    |> keep(columns: [\"_value\", \"_time\", \"cc\", \"source\", \"subscription\", \"_measurement\"])\n    |> last()\n  \t|> yield()"
      }
     ]
    }
   ]
  },
  { "title": "NCS5xxx", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Input power",
   "type": "bargauge",
   "gridPos": { "h": 29, "w": 13, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"bucket1\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => \n  \tr._measurement == \"Cisco-IOS-XR-sysadmin-fretta-envmon-ui:environment/oper/power/location/pem_attributes\" and \n    r.source != \"Lyon-23\" and\n    (\n    //r._field == \"usable_power_capacity\" or \n    //r._field == \"protection_power_capacity\" or\n    r._field == \"system_power_input\" //or \n    //r._field == \"system_power_used\"\n    )\n    )\n  //|> keep(columns: [\"_field\", \"_value\", \"_time\", \"pem\", \"location\", \"pem_id/value\", \"source\", \"confgd_power_redundancy_mode/value\"])\n  |> keep(columns: [\"_field\", \"_value\", \"_time\", \"source\"])\n  |> group()\n  |> sort(columns: [\"_time\"], desc: true)\n  |> unique(column: \"source\")\n  |> sort(columns: [\"source\"], desc: true)\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"source\"], valueColumn: \"_value\")"
    }
   ]
  },
  {
   "title": "Required power",
   "type": "stat",
   "gridPos": { "h": 29, "w": 2, "x": 13, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"bucket1\")\n  |> range(start: v.timeRangeStart)\n  |> filter(fn: (r) => \n  \tr._measurement == \"Cisco-IOS-XR-sysadmin-fretta-envmon-ui:environment/oper/power/location/pem_attributes\" and \n    r.source != \"Lyon-23\" and\n    (\n    r._field == \"power_resrv_and_alloc\"\n    ))\n  //|> keep(columns: [\"_field\", \"_value\", \"_time\", \"pem\", \"location\", \"source\", \"pem_id/value\", \"confgd_power_redundancy_mode/value\"])\n  |> keep(columns: [\"_field\", \"_value\", \"_time\", \"source\"])\n  // For sorting data (replaces |>last())\n  |> group()\n  |> sort(columns: [\"_time\"], desc: true)\n  |> unique(column: \"source\")\n  |> sort(columns: [\"source\"], desc: true)\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"source\"], valueColumn: \"_value\")"
    }
   ]
  },
  {
   "title": "Regional C emissions [g CO2 eq / kWh]",
   "type": "gauge",
   "gridPos": { "h": 29, "w": 4, "x": 16, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "massg" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "src = from(bucket: \"bucket1\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n  r._measurement == \"Cisco-IOS-XR-sysadmin-fretta-envmon-ui:environment/oper/power/location/pem_attributes\" and\n  r.source != \"Lyon-23\" and\n  r._field == \"system_power_input\")\n  |> window(every: 5m)\n  |> mean()\n  |> duplicate(column: \"_stop\", as: \"_time\")\n  |> drop(columns: [\"_stop\", \"_start\"])\n\nco2eqkwh = from(bucket: \"bucket1\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n  \t  r._measurement == \"electricity-map\" and\n      r._field == \"carbonIntensity\")\n  |> drop(columns: [\"_measurement\"])\n  |> window(every: 5m)\n  |> mean()\n  |> duplicate(column: \"_stop\", as: \"_time\")\n  |> drop(columns: [\"_stop\", \"_start\"])\n\nj = join(\n\ttables: {t1: src, t2: co2eqkwh},\n    on: [\"cc\", \"_time\"],\n\t)\n    |> map(fn: (r) => ({\n    r with\n    \tregion: r.region_t1,\n    \tcountry: r.country_t1,\n      _value: r._value_t2,\n\t}))\n    |> keep(columns: [\"_value\", \"_time\", \"cc\", \"source\", \"subscription\", \"_measurement\"])\n    // For sorting data (replaces |>last())\n    |> group()\n    |> sort(columns: [\"_time\"], desc: true)\n    |> unique(column: \"source\")\n    |> sort(columns: [\"source\"], desc: true)\n    |> pivot(rowKey:[\"_time\"], columnKey: [\"source\", \"cc\"], valueColumn: \"_value\")\n  \t|> yield()"
    }
   ]
  },
  {
   "title": "Current C emissions / h [g CO2 eq / h]",
   "type": "stat",
   "description": "//Carbon emission (extrapolated to 1h)\n\n//Gives us the carbon emissions per hour (W x gCO₂eq/kWh = (J/s) x gCO2eq / kWh = (J/s) x gCO2eq / (1000Wh) = (J/s) x gCO2eq / (3600x1000J) = JxgCO2eq/(3600sx1000J) = gCO2eq/(3600sx1000) = gCO2eq/1000h)",
   "gridPos": { "h": 29, "w": 2, "x": 20, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "massg" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "//Carbon emission (extrapolated to 1h)\n\n//Gives us the carbon emissions per hour (W x gCO₂eq/kWh = (J/s) x gCO2eq / kWh = (J/s) x gCO2eq / (1000Wh) = (J/s) x gCO2eq / (3600x1000J) = JxgCO2eq/(3600sx1000J) = gCO2eq/(3600sx1000) = gCO2eq/1000h)\n\nsrc = from(bucket: \"bucket1\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n  r._measurement == \"Cisco-IOS-XR-sysadmin-fretta-envmon-ui:environment/oper/power/location/pem_attributes\" and\n  r.source != \"Lyon-23\" and\n  r._field == \"system_power_input\")\n  |> window(every: 5m)\n  |> mean()\n  |> duplicate(column: \"_stop\", as: \"_time\")\n  |> drop(columns: [\"_stop\", \"_start\"])\n\nco2eqkwh = from(bucket: \"bucket1\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n  \t  r._measurement == \"electricity-map\" and\n      r._field == \"carbonIntensity\")\n  |> drop(columns: [\"_measurement\"])\n  |> window(every: 5m)\n  |> mean()\n  |> duplicate(column: \"_stop\", as: \"_time\")\n  |> drop(columns: [\"_stop\", \"_start\"])\n\nj = join(\n\ttables: {t1: src, t2: co2eqkwh},\n    on: [\"cc\", \"_time\"],\n\t)\n    |> map(fn: (r) => ({\n    r with\n    \tregion: r.region_t1,\n    \tcountry: r.country_t1,\n      _value: float(v: r._value_t1) * float(v: r._value_t2) / 1000.0,\n\t}))\n    |> keep(columns: [\"_value\", \"_time\", \"cc\", \"source\", \"subscription\", \"_measurement\"])\n    \n    // For sorting data (replaces |>last())\n    |> group()\n    |> sort(columns: [\"_time\"], desc: true)\n    |> unique(column: \"source\")\n    |> sort(columns: [\"source\"], desc: true)\n    |> pivot(rowKey:[\"_time\"], columnKey: [\"source\", \"cc\"], valueColumn: \"_value\")\n  \t|> yield()"
    }
   ]
  },
  { "title": "ASR 9K", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 } },
  {
   "title": "Input power",
   "type": "bargauge",
   "gridPos": { "h": 22, "w": 13, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"bucket1\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => \n  \tr._measurement == \"Cisco-IOS-XR-sysadmin-asr9k-envmon-ui:environment/oper/power/location/pem_attributes\" and \n    (\n    //r._field == \"usable_power_capacity\" or \n    //r._field == \"protection_power_capacity\" or\n    r._field == \"system_power_input\" //or \n    //r._field == \"system_power_used\"\n    )\n    )\n  //|> keep(columns: [\"_field\", \"_value\", \"_time\", \"pem\", \"location\", \"pem_id/value\", \"source\", \"confgd_power_redundancy_mode/value\"])\n  //|> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> keep(columns: [\"_field\", \"_value\", \"_time\", \"source\", \"system_power_input\"])\n  //|> group(columns: [ \"source\"])\n  //|> last(column: \"system_power_input\")\n  // For sorting data (replaces |>last())\n  |> group()\n  |> sort(columns: [\"_time\"], desc: true)\n  |> unique(column: \"source\")\n  |> sort(columns: [\"source\"], desc: true)\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"source\"], valueColumn: \"_value\")"
    }
   ]
  },
  {
   "title": "Required power",
   "type": "stat",
   "gridPos": { "h": 22, "w": 2, "x": 13, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"bucket1\")\n  |> range(start: v.timeRangeStart)\n  |> filter(fn: (r) => \n  \tr._measurement == \"Cisco-IOS-XR-sysadmin-asr9k-envmon-ui:environment/oper/power/location/pem_attributes\" and \n    (\n    r._field == \"power_resrv_and_alloc\"\n    )\n    )\n  //|> keep(columns: [\"_field\", \"_value\", \"_time\", \"pem\", \"location\", \"source\", \"pem_id/value\", \"confgd_power_redundancy_mode/value\"])\n  |> keep(columns: [\"_field\", \"_value\", \"_time\", \"source\"])\n  // For sorting data (replaces |>last())\n  |> group()\n  |> sort(columns: [\"_time\"], desc: true)\n  |> unique(column: \"source\")\n  |> sort(columns: [\"source\"], desc: true)\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"source\"], valueColumn: \"_value\")"
    }
   ]
  },
  {
   "title": "Regional C emissions [g CO2 eq / kWh]",
   "type": "gauge",
   "gridPos": { "h": 22, "w": 4, "x": 16, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "massg" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "src = from(bucket: \"bucket1\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n  r._measurement == \"Cisco-IOS-XR-sysadmin-asr9k-envmon-ui:environment/oper/power/location/pem_attributes\" and\n  r._field == \"system_power_input\")\n  |> window(every: 5m)\n  |> mean()\n  |> duplicate(column: \"_stop\", as: \"_time\")\n  |> drop(columns: [\"_stop\", \"_start\"])\n\nco2eqkwh = from(bucket: \"bucket1\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n  \t  r._measurement == \"electricity-map\" and\n      r._field == \"carbonIntensity\")\n  |> drop(columns: [\"_measurement\"])\n  |> window(every: 5m)\n  |> mean()\n  |> duplicate(column: \"_stop\", as: \"_time\")\n  |> drop(columns: [\"_stop\", \"_start\"])\n\nj = join(\n\ttables: {t1: src, t2: co2eqkwh},\n    on: [\"cc\", \"_time\"],\n\t)\n    |> map(fn: (r) => ({\n    r with\n    \tregion: r.region_t1,\n    \tcountry: r.country_t1,\n      _value: r._value_t2,\n\t}))\n    |> keep(columns: [\"_value\", \"_time\", \"cc\", \"source\", \"subscription\", \"_measurement\"])\n    \n    // For sorting data (replaces |>last())\n    |> group()\n    |> sort(columns: [\"_time\"], desc: true)\n    |> unique(column: \"source\")\n    |> sort(columns: [\"source\"], desc: true)\n    |> pivot(rowKey:[\"_time\"], columnKey: [\"source\", \"cc\"], valueColumn: \"_value\")\n  \t|> yield()"
    }
   ]
  },
  {
   "title": "Current C emissions / h [g CO2 eq / h]",
   "type": "stat",
   "gridPos": { "h": 22, "w": 2, "x": 20, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "massg" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "src = from(bucket: \"bucket1\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n  r._measurement == \"Cisco-IOS-XR-sysadmin-asr9k-envmon-ui:environment/oper/power/location/pem_attributes\" and\n  r._field == \"system_power_input\")\n  |> window(every: 5m)\n  |> mean()\n  |> duplicate(column: \"_stop\", as: \"_time\")\n  |> drop(columns: [\"_stop\", \"_start\"])\n\nco2eqkwh = from(bucket: \"bucket1\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n  \t  r._measurement == \"electricity-map\" and\n      r._field == \"carbonIntensity\")\n  |> drop(columns: [\"_measurement\"])\n  |> window(every: 5m)\n  |> mean()\n  |> duplicate(column: \"_stop\", as: \"_time\")\n  |> drop(columns: [\"_stop\", \"_start\"])\n\nj = join(\n\ttables: {t1: src, t2: co2eqkwh},\n    on: [\"cc\", \"_time\"],\n\t)\n    |> map(fn: (r) => ({\n    r with\n    \t//system_power_input: r._value_t1,\n    \t//carbonIntensity: r._value_t2,\n    \tregion: r.region_t1,\n    \tcountry: r.country_t1,\n      _value: float(v: r._value_t1) * float(v: r._value_t2) / 1000.0,\n\t}))\n    |> keep(columns: [\"_value\", \"_time\", \"cc\", \"source\", \"subscription\", \"_measurement\"])\n    // For sorting data (replaces |>last())\n    |> group()\n    |> sort(columns: [\"_time\"], desc: true)\n    |> unique(column: \"source\")\n    |> sort(columns: [\"source\"], desc: true)\n    |> pivot(rowKey:[\"_time\"], columnKey: [\"source\", \"cc\"], valueColumn: \"_value\")\n  \t|> yield()"
    }
   ]
  },
  { "title": "ASR 9K (32-bit)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 81 } },
  {
   "title": "Input power",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"bucket1\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"asr9k_power\")\n  |> sort(columns: [\"_time\", \"source\"], desc: true)\n  |> unique(column: \"source\")\n  |> pivot(columnKey: [\"_field\"], rowKey: [\"source\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({r with \" \": (r.voltage1 * r.current1 + r.voltage2 * r.current2) / 1000000}))\n  |> keep(columns: [\"_time\", \" \", \"source\"])"
    }
   ]
  },
  {
   "title": "Required power",
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 13, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"bucket1\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"asr9k_power\")\n  |> sort(columns: [\"_time\", \"source\"], desc: true)\n  |> unique(column: \"source\")\n  |> pivot(columnKey: [\"_field\"], rowKey: [\"source\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({r with \" \": (r.capacity1 + r.capacity2)}))\n  |> keep(columns: [\"_time\", \" \", \"source\"])"
    }
   ]
  },
  {
   "title": "Regional C emissions [g CO2 eq / kWh]",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "massg" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "src = from(bucket: \"bucket1\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"asr9k_power\" and r._field == \"current1\")\n  |> window(every: 5m)\n  |> mean()\n  |> duplicate(column: \"_stop\", as: \"_time\")\n  |> drop(columns: [\"_stop\", \"_start\"])\n\nco2eqkwh = from(bucket: \"bucket1\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n  \t  r._measurement == \"electricity-map\" and\n      r._field == \"carbonIntensity\")\n  |> drop(columns: [\"_measurement\"])\n  |> window(every: 5m)\n  |> mean()\n  |> duplicate(column: \"_stop\", as: \"_time\")\n  |> drop(columns: [\"_stop\", \"_start\"])\n\nj = join(\n\ttables: {t1: src, t2: co2eqkwh},\n    on: [\"cc\", \"_time\"],\n\t)\n    |> map(fn: (r) => ({\n    r with\n    \tregion: r.region_t1,\n    \tcountry: r.country_t1,\n      _value: r._value_t2,\n\t}))\n    |> keep(columns: [\"_value\", \"_time\", \"cc\", \"source\", \"subscription\", \"_measurement\"])\n    \n    // For sorting data (replaces |>last())\n    |> group()\n    |> sort(columns: [\"_time\"], desc: true)\n    |> unique(column: \"source\")\n    |> sort(columns: [\"source\"], desc: false)\n    |> pivot(rowKey:[\"_time\"], columnKey: [\"source\", \"cc\"], valueColumn: \"_value\")\n  \t|> yield()"
    }
   ]
  },
  {
   "title": "Current C emissions / h [g CO2 eq / h]",
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 20, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "massg" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "src = from(bucket: \"bucket1\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"asr9k_power\")\n  |> sort(columns: [\"_time\", \"source\"], desc: true)\n  |> unique(column: \"source\")\n  |> pivot(columnKey: [\"_field\"], rowKey: [\"source\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({r with _value: (r.voltage1 * r.current1 + r.voltage2 * r.current2) / 1000000}))\n  |> keep(columns: [\"_time\", \"_value\", \"source\", \"cc\"])\n\nco2eqkwh = from(bucket: \"bucket1\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n  \t  r._measurement == \"electricity-map\" and\n      r._field == \"carbonIntensity\")\n  |> drop(columns: [\"_measurement\"])\n\nj = join(\n\ttables: {t1: src, t2: co2eqkwh},\n    on: [\"cc\"],\n\t)\n    |> map(fn: (r) => ({\n    r with\n    \t//system_power_input: r._value_t1,\n    \t//carbonIntensity: r._value_t2,\n    \tregion: r.region_t1,\n    \tcountry: r.country_t1,\n      \" \": float(v: r._value_t1) * float(v: r._value_t2) / 1000.0,\n    \t_time: r._time_t1\n\t}))\n    // For sorting data (replaces |>last())\n    |> sort(columns: [\"_time\"], desc: true)\n    |> unique(column: \"source\")\n    |> sort(columns: [\"source\"], desc: false)\n    |> keep(columns: [\" \", \"source\"])\n  \t|> yield()"
    }
   ]
  },
  { "title": "C8K", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 90 } },
  {
   "title": "Input power",
   "type": "bargauge",
   "description": "Efficiency may be low if the power supply is at very low operation range (e.g. 100W for a 4kW power supply)",
   "gridPos": { "h": 11, "w": 13, "x": 0, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"bucket1\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => \n    r.device_type == \"cisco-8k\" and\n    r._measurement == \"Cisco-IOS-XR-envmon-oper:power-management/rack/producers/producer-nodes/producer-node\" and \n    (\n    r._field == \"pem_info_array/current_in_a\" or\n    r._field == \"pem_info_array/voltage_in_a\" or \n    r._field == \"pem_info_array/current_in_b\" or\n    r._field == \"pem_info_array/voltage_in_b\"\n    ))\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> rename(columns: {\"pem_info_array/voltage_in_a\": \"voltage_in_a\", \"pem_info_array/current_in_a\": \"current_in_a\", \"pem_info_array/voltage_in_b\": \"voltage_in_b\", \"pem_info_array/current_in_b\": \"current_in_b\"})\n  |> map(fn: (r) => ({\n    r with\n    power_in_a: if float(v: r.current_in_a) > 100 then (float(v: r.voltage_in_a)/1000.0) * (float(v: r.current_in_a)/1000.0) else float(v: r.voltage_in_a) * float(v: r.current_in_a),\n    power_in_b: if float(v: r.current_in_b) > 100 then (float(v: r.voltage_in_b)/1000.0) * (float(v: r.current_in_b)/1000.0) else float(v: r.voltage_in_b) * float(v: r.current_in_b),\n   }))\n  |> map(fn: (r) => ({\n    r with\n    _value: r.power_in_a + r.power_in_b,\n  }))\n  |> last(column: \"_value\")\n  |> group(columns:[\"source\"])\n  |> keep(columns: [\"in_power\", \"_field\", \"_value\", \"source\"])\n  |> sum(column: \"_value\")\n  // For sorting data (replaces |>last())\n  |> group()\n  //|> sort(columns: [\"_time\"], desc: true)\n  //|> unique(column: \"source\")\n  |> sort(columns: [\"source\"], desc: false)\n  |> pivot(rowKey:[], columnKey: [\"source\"], valueColumn: \"_value\")"
    }
   ]
  },
  {
   "title": "Required power",
   "type": "stat",
   "gridPos": { "h": 11, "w": 2, "x": 13, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"bucket1\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => \n    r.device_type == \"cisco-8k\" and\n    r._measurement == \"Cisco-IOS-XR-envmon-oper:power-management/rack/chassis\" and \n    (\n    //r._field == \"total_pwr_input\" or\n    //r._field == \"total_pwr_output\" or\n    //r._field == \"total_output_capacity\" or\n    r._field == \"total_pwr_required\"\n    )\n    )\n  //|> keep(columns: [\"_field\", \"_value\", \"_time\", \"name\", \"source\"])\n  |> keep(columns: [\"_field\", \"_value\", \"_time\", \"source\"])\n  // For sorting data (replaces |>last())\n  |> group()\n  |> sort(columns: [\"_time\"], desc: true)\n  |> unique(column: \"source\")\n  |> sort(columns: [\"source\"], desc: false)\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"source\"], valueColumn: \"_value\")"
    }
   ]
  },
  {
   "title": "Regional C emissions [g CO2 eq / kWh]",
   "type": "gauge",
   "gridPos": { "h": 11, "w": 4, "x": 16, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "massg" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "src = from(bucket: \"bucket1\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => \n    r.device_type == \"cisco-8k\" and\n    r._measurement == \"Cisco-IOS-XR-envmon-oper:power-management/rack/producers/producer-nodes/producer-node\" and \n    (\n    r._field == \"pem_info_array/current_in_a\" or\n    r._field == \"pem_info_array/voltage_in_a\" or \n    r._field == \"pem_info_array/current_in_b\" or\n    r._field == \"pem_info_array/voltage_in_b\"\n    ))\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> rename(columns: {\"pem_info_array/voltage_in_a\": \"voltage_in_a\", \"pem_info_array/current_in_a\": \"current_in_a\", \"pem_info_array/voltage_in_b\": \"voltage_in_b\", \"pem_info_array/current_in_b\": \"current_in_b\"})\n  |> map(fn: (r) => ({\n    r with\n    power_in_a: (float(v: r.voltage_in_a)/1000.0) * (float(v: r.current_in_a)/1000.0),\n    power_in_b: (float(v: r.voltage_in_b)/1000.0) * (float(v: r.current_in_b)/1000.0),\n   }))\n  |> map(fn: (r) => ({\n    r with\n    in_power: r.power_in_a + r.power_in_b,\n  }))\n  |> last(column: \"in_power\")\n  |> keep(columns: [\"_time\", \"in_power\", \"_field\", \"_value\", \"source\", \"cc\"])\n  //|> keep(columns: [\"_time\", \"in_power\", \"_field\", \"_value\", \"source\", \"cc\", \"node\", \"name\", \"pem_info_array/node_name\"])\n  |> sum(column: \"in_power\")\n  |> map(fn: (r) => ({\n    r with\n    _value: r.in_power,\n  }))\n\nco2eqkwh = from(bucket: \"bucket1\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n  \t  r._measurement == \"electricity-map\" and\n      r._field == \"carbonIntensity\")\n  |> drop(columns: [\"_measurement\"])\n\nj = join(\n\ttables: {t1: src, t2: co2eqkwh},\n    on: [\"cc\"],\n\t)\n    |> map(fn: (r) => ({\n    r with\n    \t//system_power_input: r.in_power,\n    \t//carbonIntensity: r._value_t2,\n    \t//region: r.region_t1,\n    \t//country: r.country_t1,\n      _value: r._value_t2,\n    \t_time: r._time_t1\n\t}))\n    //|> keep(columns: [\"_value\", \"_time\", \"cc\", \"source\", \"subscription\", \"_measurement\", \"region_t1\", \"country_t1\"])\n    |> keep(columns: [\"_value\", \"_time\", \"cc\", \"source\", \"subscription\", \"_measurement\"])\n    \n    // For sorting data (replaces |>last())\n    |> group()\n    |> sort(columns: [\"_time\"], desc: true)\n    |> unique(column: \"source\")\n    |> sort(columns: [\"source\"], desc: false)\n    |> pivot(rowKey:[], columnKey: [\"source\", \"cc\"], valueColumn: \"_value\")\n  \t|> yield()\n    \n    "
    }
   ]
  },
  {
   "title": "Current C emissions / h [g CO2 eq / h]",
   "type": "stat",
   "description": "//Carbon emission (extrapolated to 1h)\n\n//Gives us the carbon emissions per hour (W x gCO₂eq/kWh = (J/s) x gCO2eq / kWh = (J/s) x gCO2eq / (1000Wh) = (J/s) x gCO2eq / (3600x1000J) = JxgCO2eq/(3600sx1000J) = gCO2eq/(3600sx1000) = gCO2eq/1000h)",
   "gridPos": { "h": 11, "w": 2, "x": 20, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "massg" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "//Carbon emission (extrapolated to 1h)\n\n//Gives us the carbon emissions per hour (W x gCO₂eq/kWh = (J/s) x gCO2eq / kWh = (J/s) x gCO2eq / (1000Wh) = (J/s) x gCO2eq / (3600x1000J) = JxgCO2eq/(3600sx1000J) = gCO2eq/(3600sx1000) = gCO2eq/1000h)\n\nsrc = from(bucket: \"bucket1\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => \n    r.device_type == \"cisco-8k\" and\n    r._measurement == \"Cisco-IOS-XR-envmon-oper:power-management/rack/producers/producer-nodes/producer-node\" and \n    (\n    r._field == \"pem_info_array/current_in_a\" or\n    r._field == \"pem_info_array/voltage_in_a\" or \n    r._field == \"pem_info_array/current_in_b\" or\n    r._field == \"pem_info_array/voltage_in_b\"\n    ))\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> rename(columns: {\"pem_info_array/voltage_in_a\": \"voltage_in_a\", \"pem_info_array/current_in_a\": \"current_in_a\", \"pem_info_array/voltage_in_b\": \"voltage_in_b\", \"pem_info_array/current_in_b\": \"current_in_b\"})\n  |> map(fn: (r) => ({\n    r with\n    power_in_a: if float(v: r.current_in_a) > 100 then (float(v: r.voltage_in_a)/1000.0) * (float(v: r.current_in_a)/1000.0) else float(v: r.voltage_in_a) * float(v: r.current_in_a),\n    power_in_b: if float(v: r.current_in_b) > 100 then (float(v: r.voltage_in_b)/1000.0) * (float(v: r.current_in_b)/1000.0) else float(v: r.voltage_in_b) * float(v: r.current_in_b),\n   }))\n  |> map(fn: (r) => ({\n    r with\n    in_power: r.power_in_a + r.power_in_b,\n  }))\n  |> last(column: \"in_power\")\n  |> keep(columns: [\"_time\", \"in_power\", \"_field\", \"_value\", \"source\", \"cc\"])\n  //|> keep(columns: [\"_time\", \"in_power\", \"_field\", \"_value\", \"source\", \"cc\", \"node\", \"name\", \"pem_info_array/node_name\"])\n  |> sum(column: \"in_power\")\n  |> map(fn: (r) => ({\n    r with\n    _value: r.in_power,\n  }))\n\nco2eqkwh = from(bucket: \"bucket1\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n  \t  r._measurement == \"electricity-map\" and\n      r._field == \"carbonIntensity\")\n  |> drop(columns: [\"_measurement\"])\n\nj = join(\n\ttables: {t1: src, t2: co2eqkwh},\n    on: [\"cc\"],\n\t)\n    |> map(fn: (r) => ({\n    r with\n    \t//system_power_input: r.in_power,\n    \t//carbonIntensity: r._value_t2,\n    \t//region: r.region_t1,\n    \t//country: r.country_t1,\n      _value: float(v:r._value_t1) * float(v:r._value_t2) / 1000.0,\n    \t_time: r._time_t1\n\t}))\n    //|> keep(columns: [\"_value\", \"_time\", \"cc\", \"source\", \"subscription\", \"_measurement\", \"region_t1\", \"country_t1\"])\n    |> keep(columns: [\"_value\", \"_time\", \"cc\", \"source\", \"subscription\", \"_measurement\"])\n    \n    // For sorting data (replaces |>last())\n    |> group()\n    |> sort(columns: [\"_time\"], desc: true)\n    |> unique(column: \"source\")\n    |> sort(columns: [\"source\"], desc: false)\n    |> pivot(rowKey:[], columnKey: [\"source\", \"cc\"], valueColumn: \"_value\")\n  \t|> yield()\n    "
    }
   ]
  },
  { "title": "ASR 9xx (IOS XE)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 102 } },
  {
   "title": "Input power",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 103 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"bucket1\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"Cisco-IOS-XE-environment-oper:environment-sensors/environment-sensor\" and r._field == \"current_reading\" and (r.name == \"PEM Iout\" or r.name == \"PEM Vout\"))\n  |> sort(columns: [\"_time\", \"source\"], desc: true)\n  |> unique(column: \"source\")\n  |> pivot(columnKey: [\"name\"], rowKey: [\"source\", \"location\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({r with \" \": (r[\"PEM Iout\"] * r[\"PEM Vout\"])}))\n  |> group(columns: [\"source\"])\n  |> sum(column: \" \")"
    }
   ]
  },
  {
   "title": "Required power",
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 13, "y": 103 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"bucket1\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"Cisco-IOS-XE-environment-oper:environment-sensors/environment-sensor\" and r._field == \"current_reading\" and (r.name == \"PEM Iout\" or r.name == \"PEM Vout\"))\n  |> sort(columns: [\"_time\", \"source\"], desc: true)\n  |> unique(column: \"source\")\n  |> pivot(columnKey: [\"name\"], rowKey: [\"source\", \"location\"], valueColumn: \"_value\")\n  |> group(columns: [\"source\"])\n  |> map(fn:(r) => ({r with \" \": int(v: r.maxpower)}))\n  |> sum(column: \" \")"
    }
   ]
  },
  {
   "title": "Regional C emissions [g CO2 eq / kWh]",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 103 },
   "fieldConfig": { "defaults": { "unit": "massg" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "src = from(bucket: \"bucket1\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"Cisco-IOS-XE-environment-oper:environment-sensors/environment-sensor\" and r._field == \"current_reading\" and r.name == \"PEM Iout\" and r.location == \"P0\")\n  |> unique(column: \"source\")\n\nco2eqkwh = from(bucket: \"bucket1\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n  \t  r._measurement == \"electricity-map\" and\n      r._field == \"carbonIntensity\")\n  |> drop(columns: [\"_measurement\"])\n\nj = join(\n\ttables: {t1: src, t2: co2eqkwh},\n    on: [\"cc\"],\n\t)\n    |> map(fn: (r) => ({\n    r with\n    \t//system_power_input: r._value_t1,\n    \t//carbonIntensity: r._value_t2,\n    \tregion: r.region_t1,\n    \tcountry: r.country_t1,\n      _value: r._value_t2,\n    \t_time: r._time_t1\n\t}))\n    //|> keep(columns: [\"_value\", \"_time\", \"cc\", \"region\", \"country\", \"system_power_input\", \"carbonIntensity\", \"source\", \"subscription\", \"_measurement\"])\n    //|> keep(columns: [\"_value\", \"_time\", \"cc\", \"region\", \"country\", \"source\", \"subscription\", \"_measurement\", \"region_t1\", \"country_t1\"])\n    //|> keep(columns: [\"_value\", \"_time\", \"cc\", \"source\", \"subscription\", \"_measurement\", \"region_t1\", \"country_t1\"])\n    |> keep(columns: [\"_value\", \"_time\", \"cc\", \"source\", \"subscription\", \"_measurement\"])\n    \n    // For sorting data (replaces |>last())\n    |> group()\n    |> sort(columns: [\"_time\"], desc: true)\n    |> unique(column: \"source\")\n    |> sort(columns: [\"source\"], desc: false)\n    |> pivot(rowKey:[\"_time\"], columnKey: [\"source\", \"cc\"], valueColumn: \"_value\")\n  \t|> yield()"
    }
   ]
  },
  {
   "title": "Current C emissions / h [g CO2 eq / h]",
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 20, "y": 103 },
   "fieldConfig": { "defaults": { "unit": "massg" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "src = from(bucket: \"bucket1\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"Cisco-IOS-XE-environment-oper:environment-sensors/environment-sensor\" and r._field == \"current_reading\" and (r.name == \"PEM Iout\" or r.name == \"PEM Vout\"))\n  |> sort(columns: [\"_time\", \"source\"], desc: true)\n  |> unique(column: \"source\")\n  |> pivot(columnKey: [\"name\"], rowKey: [\"source\", \"location\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({r with _value: (r[\"PEM Iout\"] * r[\"PEM Vout\"])}))\n  |> group(columns: [\"source\", \"cc\"])\n  |> sum(column: \"_value\")\n\nco2eqkwh = from(bucket: \"bucket1\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n  \t  r._measurement == \"electricity-map\" and\n      r._field == \"carbonIntensity\")\n  |> drop(columns: [\"_measurement\"])\n\nj = join(\n\ttables: {t1: src, t2: co2eqkwh},\n    on: [\"cc\"],\n\t)\n    |> map(fn: (r) => ({\n    r with\n    \t//system_power_input: r._value_t1,\n    \t//carbonIntensity: r._value_t2,\n    \tregion: r.region_t1,\n    \tcountry: r.country_t1,\n      \" \": float(v: r._value_t1) * float(v: r._value_t2) / 1000.0,\n    \t_time: r._time_t1\n\t}))\n    // For sorting data (replaces |>last())\n    |> sort(columns: [\"_time\"], desc: true)\n    |> unique(column: \"source\")\n    |> sort(columns: [\"source\"], desc: false)\n    |> keep(columns: [\" \", \"source\"])\n  \t|> yield()"
    }
   ]
  }
 ]
}