{
 "title": "Fretta - Power",
 "description": "sysadmin-fretta-envmon-ui YANG model",
 "tags": [
  "NCS5xx",
  "envmon"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "host",
    "query": "import \"influxdata/influxdb/v1\"\n\nv1.measurementTagValues(\n  bucket: \"bucket1\",\n  measurement: \"Cisco-IOS-XR-sysadmin-fretta-envmon-ui:environment/oper/power/location/pem_attributes\",\n  tag: \"source\"\n)"
   }
  ]
 },
 "panels": [
  { "title": "CHASSIS LEVEL POWER INFO", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Power efficiency",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"bucket1\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => \n  \tr._measurement == \"Cisco-IOS-XR-sysadmin-fretta-envmon-ui:environment/oper/power/location/pem_attributes\" and \n    (\n    r._field == \"system_power_input\" or \n    r._field == \"system_power_used\"\n    ) and\n    r.source == \"${host}\"\n    )\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({\n    r with\n    _value: (float(v: r.system_power_used) / float(v: r.system_power_input)) * 100.0\n   }))\n  |> drop(columns: [\"system_power_used\", \"system_power_input\"])"
    }
   ]
  },
  {
   "title": "Usable capacity, protection, input and usage",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"bucket1\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => \n  \tr._measurement == \"Cisco-IOS-XR-sysadmin-fretta-envmon-ui:environment/oper/power/location/pem_attributes\" and \n    (\n    r._field == \"usable_power_capacity\" or \n    r._field == \"protection_power_capacity\" or\n    r._field == \"system_power_input\" or \n    r._field == \"system_power_used\"\n    ) and\n    r.source == \"${host}\"\n    )\n  |> keep(columns: [\"_field\", \"_value\", \"_time\", \"pem\", \"location\", \"pem_id/value\", \"source\", \"confgd_power_redundancy_mode/value\"])"
    },
    {
     "query": "from(bucket: \"bucket1\")\n  |> range(start: v.timeRangeStart)\n  |> filter(fn: (r) => \n  \tr._measurement == \"Cisco-IOS-XR-sysadmin-fretta-envmon-ui:environment/oper/power/location/pem_attributes\" and \n    (\n    r._field == \"power_resrv_and_alloc\"\n    ) and\n    r.source == \"${host}\"\n    )\n  |> keep(columns: [\"_field\", \"_value\", \"_time\", \"pem\", \"location\", \"source\", \"pem_id/value\", \"confgd_power_redundancy_mode/value\"])"
    }
   ]
  },
  {
   "title": "Usable, protection power capacity and system input and usage",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "from(bucket: \"bucket1\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => \n  \tr._measurement == \"Cisco-IOS-XR-sysadmin-fretta-envmon-ui:environment/oper/power/location/pem_attributes\" and \n    (\n    r._field == \"usable_power_capacity\" or \n    r._field == \"protection_power_capacity\" or\n    r._field == \"system_power_input\" or \n    r._field == \"system_power_used\"\n    ) and\n    r.source == \"${host}\"\n    )\n  |> keep(columns: [\"_field\", \"_value\", \"_time\", \"pem\", \"location\", \"pem_id/value\", \"confgd_power_redundancy_mode/value\", \"source\"])"
    }
   ]
  },
  {
   "title": "Reserved and allocated power",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "from(bucket: \"bucket1\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => \n  \tr._measurement == \"Cisco-IOS-XR-sysadmin-fretta-envmon-ui:environment/oper/power/location/pem_attributes\" and \n    (\n    r._field == \"power_resrv_and_alloc\"\n    ) and\n    r.source == \"${host}\"\n    )\n  |> keep(columns: [\"_field\", \"_value\", \"_time\", \"pem\", \"location\", \"source\", \"pem_id/value\", \"confgd_power_redundancy_mode/value\"])"
    }
   ]
  },
  {
   "title": "POWER DISTRIBUTION PER RESOURCE (POWER MODULES, FANS, ROUTE PROCESSORS)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 }
  },
  {
   "title": "Current status",
   "type": "state-timeline",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {
     "query": "from(bucket: \"bucket1\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => \n  \tr._measurement == \"Cisco-IOS-XR-sysadmin-fretta-envmon-ui:environment/oper/power/location/pem_attributes\" and \n    (\n    r._field == \"power_status/value\"\n    ) and\n    r.source == \"${host}\"\n    )\n  |> keep(columns: [\"_field\", \"_value\", \"_time\", \"pem\", \"location\", \"source\", \"pem_id/value\"])"
    }
   ]
  },
  {
   "title": "Power level",
   "type": "state-timeline",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 38 },
   "targets": [
    {
     "query": "from(bucket: \"bucket1\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => \n  \tr._measurement == \"Cisco-IOS-XR-sysadmin-fretta-envmon-ui:environment/oper/power/location/pem_attributes\" and \n    (\n    r._field == \"power_level\"\n    ) and\n    r.source == \"${host}\"\n    )\n  |> keep(columns: [\"_field\", \"_value\", \"_time\", \"pem\", \"location\", \"source\", \"pem_id/value\"])"
    }
   ]
  },
  {
   "title": "Power efficiency",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"bucket1\")\n  |> range(start: v.timeRangeStart)\n  |> filter(fn: (r) => \n  \tr._measurement == \"Cisco-IOS-XR-sysadmin-fretta-envmon-ui:environment/oper/power/location/pem_attributes\" and \n    (\n    r._field == \"input_power_to_ps\" or \n    r._field == \"output_power_from_ps\"\n    ) and\n    r.source == \"${host}\"\n    )\n  |> group(columns: [\"_time\", \"_start\", \"_stop\", \"_value\"], mode: \"except\")\n  |> keep(columns: [\"_field\", \"_value\", \"_time\", \"pem\", \"location\", \"source\", \"pem_id/value\"])\n  |> pivot(rowKey:[\"_time\"], columnKey:[\"_field\"], valueColumn:\"_value\")\n  |> map(fn: (r) => ({\n      r with\n      _value: float(v: r.output_power_from_ps) / float(v: r.input_power_to_ps) * 100.0\n    })\n  )\n  |> last()\n  |> drop(columns: [\"_measurement\", \"subscription\", \"host\", \"path\", \"input_power_to_ps\", \"output_power_from_ps\"])"
    }
   ]
  },
  {
   "title": "Input and output power for PS",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "from(bucket: \"bucket1\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => \n  \tr._measurement == \"Cisco-IOS-XR-sysadmin-fretta-envmon-ui:environment/oper/power/location/pem_attributes\" and \n    (\n    r._field == \"input_power_to_ps\" or \n    r._field == \"output_power_from_ps\"\n    ) and\n    r.source == \"${host}\"\n    )\n  |> keep(columns: [\"_field\", \"_value\", \"_time\", \"pem\", \"location\", \"source\", \"pem_id/value\"])"
    }
   ]
  },
  {
   "title": "(input - output) power for PS - calculated",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "from(bucket: \"bucket1\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => \n  \tr._measurement == \"Cisco-IOS-XR-sysadmin-fretta-envmon-ui:environment/oper/power/location/pem_attributes\" and \n    (\n    r._field == \"input_power_to_ps\" or \n    r._field == \"output_power_from_ps\"\n    ) and\n    r.source == \"${host}\"\n    )\n  |> group(columns: [\"_time\", \"_start\", \"_stop\", \"_value\"], mode: \"except\")\n  |> keep(columns: [\"_field\", \"_value\", \"_time\", \"pem\", \"location\", \"source\", \"pem_id/value\"])\n  |> pivot(rowKey:[\"_time\"], columnKey:[\"_field\"], valueColumn:\"_value\")\n  |> map(fn: (r) => ({\n      r with\n      _value: r.input_power_to_ps - r.output_power_from_ps\n    })\n  )\n  |> drop(columns: [\"_measurement\", \"subscription\", \"host\", \"path\", \"input_power_to_ps\", \"output_power_from_ps\"])"
    }
   ]
  },
  {
   "title": "Allocated power",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "from(bucket: \"bucket1\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => \n  \tr._measurement == \"Cisco-IOS-XR-sysadmin-fretta-envmon-ui:environment/oper/power/location/pem_attributes\" and \n    (\n    r._field == \"power_allocated\" or\n    r._field == \"power_consumed/value\"\n    ) and\n    r.source == \"${host}\"\n    )\n  |> keep(columns: [\"_field\", \"_value\", \"_time\", \"pem\", \"location\", \"source\"])"
    }
   ]
  }
 ]
}